/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 03976285d8cc8d47bb6f00f1551c0d73)
interface __BaseEnv_Env {
	APP_ENV: "staging";
	SUPABASE_URL: "https://zqhcxudpfwsfuokencvy.supabase.co";
	SUPABASE_PUBLISHABLE_KEY: "sb_publishable_9KqTRvRzAYxDAPWAzMDRTA_9QhasRgx";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./workers/app");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_ENV" | "SUPABASE_URL" | "SUPABASE_PUBLISHABLE_KEY">> {}
}
