/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 024c40d38b3433e2f15848c9964e4c0c)
interface __BaseEnv_Env {
	APP_ENV: "beta" | "production";
	APP_BASE_URL: "https://zeyhermutter.playsony.workers.dev" | "https://SET_PRODUCTION_DOMAIN";
	SUPABASE_URL: "https://zqhcxudpfwsfuokencvy.supabase.co" | "https://SET_PRODUCTION_PROJECT_REF.supabase.co";
	SUPABASE_PUBLISHABLE_KEY: "sb_publishable_9KqTRvRzAYxDAPWAzMDRTA_9QhasRgx" | "SET_PRODUCTION_PUBLISHABLE_KEY";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./workers/app");
	}
	interface BetaEnv {
		APP_ENV: "beta";
		APP_BASE_URL: "https://zeyhermutter.playsony.workers.dev";
		SUPABASE_URL: "https://zqhcxudpfwsfuokencvy.supabase.co";
		SUPABASE_PUBLISHABLE_KEY: "sb_publishable_9KqTRvRzAYxDAPWAzMDRTA_9QhasRgx";
	}
	interface ProductionEnv {
		APP_ENV: "production";
		APP_BASE_URL: "https://SET_PRODUCTION_DOMAIN";
		SUPABASE_URL: "https://SET_PRODUCTION_PROJECT_REF.supabase.co";
		SUPABASE_PUBLISHABLE_KEY: "SET_PRODUCTION_PUBLISHABLE_KEY";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_ENV" | "APP_BASE_URL" | "SUPABASE_URL" | "SUPABASE_PUBLISHABLE_KEY">> {}
}
