/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 19cd5d19445c15d7e47687302784bc0a)
interface __BaseEnv_Env {
	APP_ENV: "beta" | "production";
	APP_BASE_URL: "https://zeyhermutter.playsony.workers.dev" | "https://zeyhermutter-production.playsony.workers.dev";
	SUPABASE_URL: "https://zqhcxudpfwsfuokencvy.supabase.co" | "https://vtmtxaaojbqqzwxkodye.supabase.co";
	SUPABASE_PUBLISHABLE_KEY: "sb_publishable_9KqTRvRzAYxDAPWAzMDRTA_9QhasRgx" | "sb_publishable_aKJnsv7nAwRSPerPU11vkg_ZsQOCjAl";
}
declare namespace Cloudflare {
	interface BetaEnv {
		APP_ENV: "beta";
		APP_BASE_URL: "https://zeyhermutter.playsony.workers.dev";
		SUPABASE_URL: "https://zqhcxudpfwsfuokencvy.supabase.co";
		SUPABASE_PUBLISHABLE_KEY: "sb_publishable_9KqTRvRzAYxDAPWAzMDRTA_9QhasRgx";
	}
	interface ProductionEnv {
		APP_ENV: "production";
		APP_BASE_URL: "https://zeyhermutter-production.playsony.workers.dev";
		SUPABASE_URL: "https://vtmtxaaojbqqzwxkodye.supabase.co";
		SUPABASE_PUBLISHABLE_KEY: "sb_publishable_aKJnsv7nAwRSPerPU11vkg_ZsQOCjAl";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_ENV" | "APP_BASE_URL" | "SUPABASE_URL" | "SUPABASE_PUBLISHABLE_KEY">> {}
}
