import { useState } from "react";
import { Form, Link } from "react-router";

const STATUS:Record<string,string>={OPEN:"Offen",IN_PROGRESS:"In Bearbeitung",DONE:"Erledigt",CANCELLED:"Abgebrochen"};
const PRIORITY:Record<string,string>={LOW:"Niedrig",NORMAL:"Normal",HIGH:"Hoch",URGENT:"Dringend"};
function formatDate(v:string|null){if(!v)return"—";return new Intl.DateTimeFormat("de-DE",{dateStyle:"medium",timeStyle:"short",timeZone:"Europe/Berlin"}).format(new Date(v));}
export type ModalTask={id:string;task_number:string;title:string;description?:string|null;status:string;priority:string;due_at:string|null;responsible_user?:string|null;version?:number;};
type Props={task:ModalTask;responsibleName?:string;contextLabel?:string;contextHref?:string;canWrite?:boolean};
export function TaskModal({task,responsibleName,contextLabel,contextHref,canWrite=true}:Props){const [open,setOpen]=useState(false);return <><button className="secondary-button compact task-open-button" type="button" onClick={()=>setOpen(true)}>Aufgabe öffnen</button>{open?<div className="module04-modal-backdrop" role="presentation" onMouseDown={(e)=>{if(e.target===e.currentTarget)setOpen(false);}}><section className="module04-modal" role="dialog" aria-modal="true" aria-labelledby={`task-${task.id}`}><div className="module04-modal-head"><div><p className="eyebrow">{task.task_number}</p><h2 id={`task-${task.id}`}>{task.title}</h2></div><button className="module04-modal-close" type="button" onClick={()=>setOpen(false)} aria-label="Schließen">×</button></div><div className="module04-modal-grid"><div className="module04-modal-field"><span>Status</span><strong>{STATUS[task.status]??task.status}</strong></div><div className="module04-modal-field"><span>Priorität</span><strong>{PRIORITY[task.priority]??task.priority}</strong></div><div className="module04-modal-field"><span>Fällig</span><strong>{formatDate(task.due_at)}</strong></div><div className="module04-modal-field"><span>Verantwortlich</span><strong>{responsibleName??"—"}</strong></div></div>{task.description?<div className="module04-modal-description">{task.description}</div>:null}{contextLabel&&contextHref?<p><Link className="subtle-link" to={contextHref}>{contextLabel} öffnen →</Link></p>:null}{canWrite?<div className="module04-modal-actions"><Form method="post"><input type="hidden" name="_intent" value="task_status"/><input type="hidden" name="task_id" value={task.id}/><input type="hidden" name="task_version" value={task.version??1}/>{task.status!=="OPEN"?<button className="secondary-button compact" name="task_status" value="OPEN" type="submit">Wieder öffnen</button>:null}{task.status==="OPEN"?<button className="secondary-button compact" name="task_status" value="IN_PROGRESS" type="submit">In Bearbeitung</button>:null}{["OPEN","IN_PROGRESS"].includes(task.status)?<button className="primary-button" name="task_status" value="DONE" type="submit">Erledigt</button>:null}</Form></div>:null}</section></div>:null}</>}
