import { useMemo, useState } from "react";
import { Form, Link } from "react-router";
import { MentionPicker } from "~/components/mention-picker";
import "~/task-collaboration.css";

const STATUS:Record<string,string>={OPEN:"Offen",IN_PROGRESS:"In Bearbeitung",DONE:"Erledigt",CANCELLED:"Abgebrochen"};
const PRIORITY:Record<string,string>={LOW:"Niedrig",NORMAL:"Normal",HIGH:"Hoch",URGENT:"Dringend"};
function formatDate(v:string|null){if(!v)return"—";return new Intl.DateTimeFormat("de-DE",{dateStyle:"medium",timeStyle:"short",timeZone:"Europe/Berlin"}).format(new Date(v));}
function dateInputValue(v:string|null){return v?new Date(v).toISOString().slice(0,10):"";}
export type ModalTask={id:string;task_number:string;title:string;description?:string|null;status:string;priority:string;due_at:string|null;responsible_user?:string|null;created_by?:string|null;version?:number;};
export type TaskWatcher={user_id:string;created_at?:string|null};
export type TaskComment={id:string;body:string;author_user_id:string;created_at:string};
type ProfileOption={user_id:string;display_name:string};
type Props={task:ModalTask;responsibleName?:string;contextLabel?:string;contextHref?:string;canWrite?:boolean;profiles?:ProfileOption[];watchers?:TaskWatcher[];comments?:TaskComment[];profileMap?:Record<string,string>};
export function TaskModal({task,responsibleName,contextLabel,contextHref,canWrite=true,profiles,watchers=[],comments=[],profileMap={}}:Props){
 const [open,setOpen]=useState(false);
 const collaborationEnabled=Array.isArray(profiles);
 const watcherIds=useMemo(()=>new Set(watchers.map(w=>w.user_id)),[watchers]);
 const availableWatchers=(profiles??[]).filter(p=>p.user_id!==task.responsible_user&&!watcherIds.has(p.user_id));
 const participantIds=useMemo(()=>Array.from(new Set([task.created_by,task.responsible_user,...watchers.map(w=>w.user_id),...comments.map(c=>c.author_user_id)].filter(Boolean) as string[])),[task.created_by,task.responsible_user,watchers,comments]);
 const nameFor=(id:string)=>profileMap[id]??profiles?.find(p=>p.user_id===id)?.display_name??"Benutzer";
 const roleFor=(id:string)=>id===task.responsible_user?"Verantwortlich":watcherIds.has(id)?"Beobachter":id===task.created_by?"Ersteller":"Beteiligt";
 return <><button className="secondary-button compact task-open-button" type="button" onClick={()=>setOpen(true)}>Aufgabe öffnen</button>{open?<div className="module04-modal-backdrop" role="presentation" onMouseDown={(e)=>{if(e.target===e.currentTarget)setOpen(false);}}><section className={`module04-modal ${collaborationEnabled?"task-collaboration-modal":""}`} role="dialog" aria-modal="true" aria-labelledby={`task-${task.id}`}><div className="module04-modal-head"><div><p className="eyebrow">{task.task_number}</p><h2 id={`task-${task.id}`}>{task.title}</h2></div><button className="module04-modal-close" type="button" onClick={()=>setOpen(false)} aria-label="Schließen">×</button></div><div className="module04-modal-grid"><div className="module04-modal-field"><span>Status</span><strong>{STATUS[task.status]??task.status}</strong></div><div className="module04-modal-field"><span>Priorität</span><strong>{PRIORITY[task.priority]??task.priority}</strong></div><div className="module04-modal-field"><span>Fällig</span><strong>{formatDate(task.due_at)}</strong></div><div className="module04-modal-field"><span>Verantwortlich</span><strong>{responsibleName??"—"}</strong></div></div>{task.description?<div className="module04-modal-description">{task.description}</div>:null}{contextLabel&&contextHref?<p><Link className="subtle-link" to={contextHref}>{contextLabel} öffnen →</Link></p>:null}
 {collaborationEnabled?<div className="task-collaboration-stack">
  <section className="task-collaboration-section"><div className="task-collaboration-head"><div><p className="eyebrow">Zusammenarbeit</p><h3>Beteiligte</h3></div><small>{participantIds.length} Person{participantIds.length===1?"":"en"}</small></div><div className="task-participant-list">{participantIds.map(id=><span className="task-participant-chip" key={id}><strong>{nameFor(id)}</strong><small>{roleFor(id)}</small></span>)}</div></section>
  <section className="task-collaboration-section"><div className="task-collaboration-head"><div><p className="eyebrow">Beobachter</p><h3>Aufgabe verfolgen</h3></div><small>Verantwortlichkeit bleibt separat.</small></div><div className="task-watcher-list">{watchers.map(w=><div className="task-watcher-row" key={w.user_id}><span><strong>{nameFor(w.user_id)}</strong><small>Beobachter</small></span>{canWrite?<Form method="post"><input type="hidden" name="_intent" value="task_watcher_remove"/><input type="hidden" name="task_id" value={task.id}/><input type="hidden" name="watcher_user_id" value={w.user_id}/><button className="text-button" type="submit">Entfernen</button></Form>:null}</div>)}{watchers.length===0?<p className="empty-state">Noch keine Beobachter.</p>:null}</div>{canWrite&&availableWatchers.length>0?<Form method="post" className="task-collaboration-inline-form"><input type="hidden" name="_intent" value="task_watcher_add"/><input type="hidden" name="task_id" value={task.id}/><select name="watcher_user_id" required defaultValue=""><option value="" disabled>Beobachter auswählen</option>{availableWatchers.map(p=><option key={p.user_id} value={p.user_id}>{p.display_name}</option>)}</select><button className="secondary-button compact" type="submit">Hinzufügen</button></Form>:null}</section>
  {canWrite?<section className="task-collaboration-section"><div className="task-collaboration-head"><div><p className="eyebrow">Fälligkeit</p><h3>Termin ändern</h3></div></div><Form method="post" className="task-collaboration-inline-form"><input type="hidden" name="_intent" value="task_due"/><input type="hidden" name="task_id" value={task.id}/><input type="hidden" name="task_version" value={task.version??1}/><input name="due_date" type="date" defaultValue={dateInputValue(task.due_at)} required/><button className="secondary-button compact" type="submit">Fälligkeit speichern</button></Form></section>:null}
  <section className="task-collaboration-section"><div className="task-collaboration-head"><div><p className="eyebrow">Kommentare</p><h3>Aufgabenverlauf</h3></div><small>{comments.length} Kommentar{comments.length===1?"":"e"}</small></div>{canWrite?<Form method="post" className="task-comment-form"><input type="hidden" name="_intent" value="task_comment"/><input type="hidden" name="task_id" value={task.id}/><textarea name="body" rows={3} required placeholder="Interner Kommentar"/><MentionPicker users={profiles??[]}/><button className="secondary-button compact" type="submit">Kommentar speichern</button></Form>:null}<div className="task-comment-list">{comments.map(c=><article className="task-comment" key={c.id}><div><strong>{nameFor(c.author_user_id)}</strong><small>{formatDate(c.created_at)}</small></div><p>{c.body}</p></article>)}{comments.length===0?<p className="empty-state">Noch keine Kommentare.</p>:null}</div></section>
 </div>:null}
 {canWrite?<div className="module04-modal-actions"><Form method="post"><input type="hidden" name="_intent" value="task_status"/><input type="hidden" name="task_id" value={task.id}/><input type="hidden" name="task_version" value={task.version??1}/>{task.status!=="OPEN"?<button className="secondary-button compact" name="task_status" value="OPEN" type="submit">Wieder öffnen</button>:null}{task.status==="OPEN"?<button className="secondary-button compact" name="task_status" value="IN_PROGRESS" type="submit">In Bearbeitung</button>:null}{["OPEN","IN_PROGRESS"].includes(task.status)?<button className="primary-button" name="task_status" value="DONE" type="submit">Erledigt</button>:null}</Form></div>:null}</section></div>:null}</>;
}
