import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  index("routes/home.tsx"),
  route("login", "routes/login.tsx"),
  route("crm", "routes/crm-dashboard.tsx"),
  route("crm/search", "routes/crm-search.tsx"),
  route("crm/tasks", "routes/tasks.tsx"),
  route("crm/notifications", "routes/notifications.tsx"),
  route("crm/history", "routes/audit-history.tsx"),
  route("crm/archive", "routes/crm-archive.tsx"),
  route("crm/contacts/new", "routes/contact-new.tsx"),
  route("crm/contacts/:contactId", "routes/contact-detail.tsx"),
  route("crm/contacts/:contactId/relations", "routes/contact-relations.tsx"),
  route("crm/contacts/:contactId/associations", "routes/contact-associations.tsx"),
  route("crm/contacts/:contactId/collaboration", "routes/contact-collaboration.tsx"),
  route("crm/organizations", "routes/organizations.tsx"),
  route("crm/organizations/:organizationId", "routes/organization-detail.tsx"),
  route("leads", "routes/leads.tsx"),
  route("leads/new", "routes/lead-new.tsx"),
  route("leads/:leadId", "routes/lead-detail.tsx"),
  route("search-profiles", "routes/search-profiles.tsx"),
  route("search-profiles/new", "routes/search-profile-new.tsx"),
  route("search-profiles/:searchProfileId", "routes/search-profile-detail.tsx"),
  route("inquiries", "routes/inquiries.tsx"),
  route("inquiries/new", "routes/inquiry-new.tsx"),
  route("inquiries/:inquiryId", "routes/inquiry-detail.tsx"),
  route("viewings", "routes/viewings.tsx"),
  route("viewings/new", "routes/viewing-new.tsx"),
  route("viewings/:viewingId", "routes/viewing-detail.tsx"),
  route("properties", "routes/properties.tsx"),
  route("properties/new", "routes/property-new.tsx"),
  route("properties/:propertyId", "routes/property-detail.tsx"),
  route("properties/:propertyId/documents", "routes/property-documents.tsx"),
  route("properties/:propertyId/media", "routes/property-media.tsx"),
  route("api/geocode-address", "routes/api-geocode-address.ts"),
  route("logout", "routes/logout.tsx"),
] satisfies RouteConfig;
