import { type RouteConfig, index, layout, route } from "@react-router/dev/routes";

export default [
  index("routes/home.tsx"),
  route("robots.txt", "routes/robots.ts"),
  route("favicon.svg", "routes/favicon.ts"),
  route("sitemap.xml", "routes/sitemap.ts"),
  route("verkaufsfertig-check", "routes/public-sales-readiness.tsx"),
  route("homepage-varianten", "routes/homepage-variants.tsx"),
  route("homepage-varianten/:variant", "routes/homepage-variant.tsx"),
  route("immobilien", "routes/public-properties.tsx"),
  route("immobilien/medien/:mediaId/:version", "routes/public-media.ts"),
  route("immobilien/:slug", "routes/public-property-detail.tsx"),
  route("kontakt", "routes/public-contact.tsx"),
  route("impressum", "routes/public-imprint.tsx"),
  route("datenschutz", "routes/public-privacy.tsx"),
  route("login", "routes/login.tsx"),
  layout("routes/internal-layout.tsx", [
    route("crm", "routes/crm-dashboard.tsx"),
    route("crm/search", "routes/crm-search.tsx"),
    route("crm/tasks", "routes/tasks.tsx"),
    route("crm/sales-readiness", "routes/sales-readiness-overview.tsx"),
    route("crm/notifications", "routes/notifications.tsx"),
    route("crm/history", "routes/audit-history.tsx"),
    route("crm/archive", "routes/crm-archive.tsx"),
    route("crm/contacts/new", "routes/contact-new.tsx"),
    route("crm/contacts/:contactId", "routes/contact-detail.tsx"),
    route("crm/contacts/:contactId/relations", "routes/contact-relations.tsx"),
    route("crm/contacts/:contactId/associations", "routes/contact-associations.tsx"),
    route("crm/contacts/:contactId/collaboration", "routes/contact-collaboration.tsx"),
    route("crm/organizations", "routes/organizations.tsx"),
    route("crm/organizations/:organizationId", "routes/organization-detail.tsx"),
    route("leads", "routes/leads.tsx"),
    route("leads/new", "routes/lead-new.tsx"),
    route("leads/:leadId", "routes/lead-detail.tsx"),
    route("leads/:leadId/sales-readiness", "routes/lead-sales-readiness.tsx"),
    route("search-profiles", "routes/search-profiles.tsx"),
    route("search-profiles/new", "routes/search-profile-new.tsx"),
    route("search-profiles/:searchProfileId", "routes/search-profile-detail.tsx"),
    route("inquiries", "routes/inquiries.tsx"),
    route("inquiries/new", "routes/inquiry-new.tsx"),
    route("inquiries/:inquiryId", "routes/inquiry-detail.tsx"),
    route("viewings", "routes/viewings.tsx"),
    route("viewings/new", "routes/viewing-new.tsx"),
    route("viewings/:viewingId", "routes/viewing-detail.tsx"),
    route("properties", "routes/properties.tsx"),
    route("properties/new", "routes/property-new.tsx"),
    route("properties/:propertyId", "routes/property-detail.tsx"),
    route("properties/:propertyId/interests", "routes/property-interests.tsx"),
    route("properties/:propertyId/publication", "routes/property-publication.tsx"),
    route("properties/:propertyId/publication/preview", "routes/property-publication-preview.tsx"),
    route("properties/:propertyId/exposes", "routes/property-exposes.tsx"),
    route("properties/:propertyId/documents", "routes/property-documents.tsx"),
    route("properties/:propertyId/media", "routes/property-media.tsx"),
  ]),
  route("__preview/sales-readiness", "routes/sales-readiness-preview.tsx"),
  route("api/sales-readiness-ai", "routes/api-sales-readiness-ai.ts"),
  route("api/geocode-address", "routes/api-geocode-address.ts"),
  route("logout", "routes/logout.tsx"),
] satisfies RouteConfig;