import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";
import { PDFDocument, StandardFonts, rgb } from "npm:pdf-lib@1.17.1";

const GENERATOR_VERSION=1;
const BUCKET="zm-private-exposes";
function response(body:unknown,status=200){return new Response(JSON.stringify(body),{status,headers:{"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"}});}
function safeText(value:unknown){return String(value??"").replace(/[–—]/g,"-").replace(/[“”„]/g,'"').replace(/[‘’]/g,"'").replace(/…/g,"...").replace(/[^\x20-\x7E\u00A0-\u00FF€]/g," ").replace(/\s+/g," ").trim();}
function money(v:unknown){const n=Number(v);return Number.isFinite(n)?`${new Intl.NumberFormat("de-DE",{maximumFractionDigits:0}).format(n)} EUR`:"Preis auf Anfrage";}
function num(v:unknown,suffix=""){const n=Number(v);return Number.isFinite(n)&&n>0?`${new Intl.NumberFormat("de-DE",{maximumFractionDigits:1}).format(n)}${suffix}`:"-";}
function wrap(text:string,font:any,size:number,maxWidth:number){const words=safeText(text).split(" ").filter(Boolean);const lines:string[]=[];let line="";for(const word of words){const next=line?`${line} ${word}`:word;if(font.widthOfTextAtSize(next,size)<=maxWidth)line=next;else{if(line)lines.push(line);line=word;}}if(line)lines.push(line);return lines;}
function hex(bytes:ArrayBuffer){return Array.from(new Uint8Array(bytes)).map(v=>v.toString(16).padStart(2,"0")).join("");}
async function sha256(bytes:Uint8Array){const copy=new Uint8Array(bytes);return hex(await crypto.subtle.digest("SHA-256",copy.buffer));}

Deno.serve(async(req:Request)=>{
 if(req.method!=="POST")return response({ok:false},405);
 const url=Deno.env.get("SUPABASE_URL"),anon=Deno.env.get("SUPABASE_ANON_KEY"),auth=req.headers.get("Authorization")??"";
 if(!url||!anon||!auth)return response({ok:false},401);
 const userDb=createClient(url,anon,{global:{headers:{Authorization:auth}},auth:{persistSession:false,autoRefreshToken:false}});
 const {data:userRes,error:userError}=await userDb.auth.getUser();const user=userRes?.user;if(userError||!user)return response({ok:false},401);
 const {data:canWrite}=await userDb.rpc("current_user_has_permission",{p_permission:"expose.write"});if(canWrite!==true)return response({ok:false,error:"FORBIDDEN"},403);
 let body:any;try{body=await req.json();}catch{return response({ok:false,error:"INVALID_REQUEST"},400);}
 const publicationVersionId=String(body.publication_version_id??"");if(!publicationVersionId)return response({ok:false,error:"VERSION_REQUIRED"},400);
 const {data:existing}=await userDb.from("property_exposes").select("id,expose_number,version_number,status").eq("publication_version_id",publicationVersionId).eq("generator_version",GENERATOR_VERSION).maybeSingle();if(existing)return response({ok:true,expose:existing,reused:true});
 const {data:version,error:versionError}=await userDb.from("property_publication_versions").select("id,public_title,teaser,snapshot,approved_at,published_at,version_number").eq("id",publicationVersionId).not("approved_at","is",null).maybeSingle();if(versionError||!version)return response({ok:false,error:"APPROVED_PUBLICATION_VERSION_REQUIRED"},400);
 const s:any=version.snapshot??{},propertyId=String(s.property_id??"");if(!propertyId)return response({ok:false,error:"INVALID_SNAPSHOT"},400);
 const pdf=await PDFDocument.create();const serif=await pdf.embedFont(StandardFonts.TimesRoman);const serifBold=await pdf.embedFont(StandardFonts.TimesRomanBold);const sans=await pdf.embedFont(StandardFonts.Helvetica);const sansBold=await pdf.embedFont(StandardFonts.HelveticaBold);
 const pageSize:[number,number]=[595.28,841.89],margin=48,contentWidth=pageSize[0]-margin*2;
 const addFooter=(page:any,pageNo:number)=>{page.drawLine({start:{x:margin,y:35},end:{x:pageSize[0]-margin,y:35},thickness:.5,color:rgb(.75,.76,.74)});page.drawText(`ZeyherMutter · ${safeText(s.property_number??"")} · Seite ${pageNo}`,{x:margin,y:20,size:8,font:sans,color:rgb(.35,.4,.4)});};
 let pageNo=1;let page=pdf.addPage(pageSize);page.drawText("ZEYHERMUTTER",{x:margin,y:790,size:10,font:sansBold,color:rgb(.22,.3,.3),characterSpacing:1.5});page.drawText(safeText(version.public_title),{x:margin,y:720,size:28,font:serifBold,color:rgb(.09,.13,.13),maxWidth:contentWidth});if(s.subtitle)page.drawText(safeText(s.subtitle),{x:margin,y:684,size:15,font:serif,color:rgb(.32,.38,.38),maxWidth:contentWidth});
 const media=Array.isArray(s.media)?s.media:[];const main=media[0];if(main?.id&&main?.source_version){const path=`media/${main.id}/v${main.source_version}`;const {data:blob}=await userDb.storage.from("zm-public-media").download(path);if(blob){try{const bytes=new Uint8Array(await blob.arrayBuffer());let img:any=null;if(blob.type==="image/jpeg")img=await pdf.embedJpg(bytes);else if(blob.type==="image/png")img=await pdf.embedPng(bytes);if(img){const boxW=contentWidth,boxH=300,scale=Math.min(boxW/img.width,boxH/img.height);const w=img.width*scale,h=img.height*scale;page.drawImage(img,{x:margin+(boxW-w)/2,y:355+(boxH-h)/2,width:w,height:h});}}catch{}}}
 page.drawText(money(s.price),{x:margin,y:320,size:20,font:sansBold,color:rgb(.09,.13,.13)});const address=s.address??{};const location=safeText([address.postal_code,address.city,address.district].filter(Boolean).join(" · ")||"Lage auf Anfrage");page.drawText(location,{x:margin,y:294,size:11,font:sans,color:rgb(.35,.4,.4)});
 const facts=[`Wohnfläche: ${num(s.living_area_sqm," m²")}`,`Zimmer: ${num(s.rooms)}`,`Grundstück: ${num(s.plot_area_sqm," m²")}`,`Baujahr: ${s.year_built??"-"}`];page.drawText(facts.join("   |   "),{x:margin,y:265,size:9.5,font:sans,color:rgb(.2,.27,.27),maxWidth:contentWidth});addFooter(page,pageNo);
 const sections=[{title:"Objektbeschreibung",text:s.description},{title:"Lage",text:s.location_description},{title:"Ausstattung",text:s.features_description}].filter(x=>safeText(x.text));for(const section of sections){pageNo++;page=pdf.addPage(pageSize);page.drawText(section.title,{x:margin,y:770,size:24,font:serifBold,color:rgb(.09,.13,.13)});let y=730;for(const line of wrap(String(section.text),sans,10.5,contentWidth)){if(y<65){addFooter(page,pageNo);pageNo++;page=pdf.addPage(pageSize);y=770;}page.drawText(line,{x:margin,y,size:10.5,font:sans,color:rgb(.22,.28,.28)});y-=16;}addFooter(page,pageNo);}
 if(Array.isArray(s.highlights)&&s.highlights.length){pageNo++;page=pdf.addPage(pageSize);page.drawText("Highlights & Eckdaten",{x:margin,y:770,size:24,font:serifBold,color:rgb(.09,.13,.13)});let y=728;for(const item of s.highlights.slice(0,18)){for(const line of wrap(`- ${item}`,sans,10.5,contentWidth)){page.drawText(line,{x:margin,y,size:10.5,font:sans,color:rgb(.22,.28,.28)});y-=16;}}y-=16;const features=Array.isArray(s.features)?s.features.filter((f:any)=>f.type!=="BOOLEAN"||f.value===true).slice(0,24):[];for(const f of features){const label=`${safeText(f.label)}${f.type!=="BOOLEAN"&&f.value!=null?`: ${safeText(f.value)}${f.unit?` ${safeText(f.unit)}`:""}`:""}`;if(y<70)break;page.drawText(label,{x:margin,y,size:9.5,font:sans,color:rgb(.25,.31,.31)});y-=14;}addFooter(page,pageNo);}
 const gallery=media.slice(1,7);for(let i=0;i<gallery.length;i+=2){pageNo++;page=pdf.addPage(pageSize);page.drawText("Impressionen",{x:margin,y:790,size:22,font:serifBold,color:rgb(.09,.13,.13)});for(let j=0;j<2;j++){const item=gallery[i+j];if(!item)continue;const path=`media/${item.id}/v${item.source_version}`;const {data:blob}=await userDb.storage.from("zm-public-media").download(path);if(!blob)continue;try{const bytes=new Uint8Array(await blob.arrayBuffer());let img:any=null;if(blob.type==="image/jpeg")img=await pdf.embedJpg(bytes);else if(blob.type==="image/png")img=await pdf.embedPng(bytes);if(!img)continue;const boxW=contentWidth,boxH=315,top=740-j*350,scale=Math.min(boxW/img.width,boxH/img.height);const w=img.width*scale,h=img.height*scale;page.drawImage(img,{x:margin+(boxW-w)/2,y:top-boxH+(boxH-h)/2,width:w,height:h});if(item.title)page.drawText(safeText(item.title),{x:margin,y:top-boxH-16,size:8.5,font:sans,color:rgb(.38,.43,.43)});}catch{}}addFooter(page,pageNo);}
 pageNo++;page=pdf.addPage(pageSize);page.drawText("Energie & Hinweise",{x:margin,y:770,size:24,font:serifBold,color:rgb(.09,.13,.13)});let y=725;if(s.energy){const energy=[s.energy.efficiency_class?`Effizienzklasse: ${s.energy.efficiency_class}`:null,s.energy.energy_value_kwh?`Energiekennwert: ${s.energy.energy_value_kwh} kWh/(m²·a)`:null,s.energy.energy_source?`Energieträger: ${s.energy.energy_source}`:null].filter(Boolean);for(const line of energy){page.drawText(safeText(line),{x:margin,y,size:10.5,font:sans,color:rgb(.22,.28,.28)});y-=18;}}y-=25;const legal="Alle Angaben beruhen auf den zum Zeitpunkt der Freigabe vorliegenden Informationen. Dieses Exposé bildet die freigegebene Publikationsversion ab. Irrtum und Zwischenverwertung bleiben vorbehalten.";for(const line of wrap(legal,sans,9.5,contentWidth)){page.drawText(line,{x:margin,y,size:9.5,font:sans,color:rgb(.38,.43,.43)});y-=15;}addFooter(page,pageNo);
 const pdfBytes=await pdf.save({useObjectStreams:false});const digest=await sha256(pdfBytes);const id=crypto.randomUUID(),path=`properties/${propertyId}/exposes/${id}.pdf`,filename=`Expose-${safeText(s.property_number??"Immobilie")}-Publikation-${version.version_number}.pdf`;
 const {error:uploadError}=await userDb.storage.from(BUCKET).upload(path,new Blob([pdfBytes],{type:"application/pdf"}),{contentType:"application/pdf",upsert:false});if(uploadError)return response({ok:false,error:"UPLOAD_FAILED"},500);
 const {data:created,error:insertError}=await userDb.from("property_exposes").insert({property_id:propertyId,publication_version_id:publicationVersionId,generator_version:GENERATOR_VERSION,version_number:1,storage_bucket:BUCKET,storage_path:path,original_filename:filename,mime_type:"application/pdf",file_size_bytes:pdfBytes.byteLength,sha256:digest,generated_by:user.id,updated_by:user.id}).select("id,expose_number,version_number,status").single();
 if(insertError||!created){await userDb.storage.from(BUCKET).remove([path]);const {data:race}=await userDb.from("property_exposes").select("id,expose_number,version_number,status").eq("publication_version_id",publicationVersionId).eq("generator_version",GENERATOR_VERSION).maybeSingle();if(race)return response({ok:true,expose:race,reused:true});return response({ok:false,error:"REGISTER_FAILED"},500);}
 return response({ok:true,expose:created});
});
