import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2.112.4";
import { PDFDocument, StandardFonts, rgb } from "npm:pdf-lib@1.17.1";

const GENERATOR_VERSION=2;
const BUCKET="zm-private-exposes";
function response(body:unknown,status=200){return new Response(JSON.stringify(body),{status,headers:{"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"}});}
function safeText(value:unknown){return String(value??"").replace(/[–—]/g,"-").replace(/[“”„]/g,'"').replace(/[‘’]/g,"'").replace(/…/g,"...").replace(/[^\x20-\x7E\u00A0-\u00FF€²]/g," ").replace(/\s+/g," ").trim();}
function money(v:unknown){const n=Number(v);return Number.isFinite(n)?`${new Intl.NumberFormat("de-DE",{maximumFractionDigits:0}).format(n)} EUR`:"Preis auf Anfrage";}
function num(v:unknown,suffix=""){const n=Number(v);return Number.isFinite(n)&&n>0?`${new Intl.NumberFormat("de-DE",{maximumFractionDigits:1}).format(n)}${suffix}`:"-";}
function wrap(text:string,font:any,size:number,maxWidth:number){const words=safeText(text).split(" ").filter(Boolean);const lines:string[]=[];let line="";for(const word of words){const next=line?`${line} ${word}`:word;if(font.widthOfTextAtSize(next,size)<=maxWidth)line=next;else{if(line)lines.push(line);line=word;}}if(line)lines.push(line);return lines;}
function hex(bytes:ArrayBuffer){return Array.from(new Uint8Array(bytes)).map(v=>v.toString(16).padStart(2,"0")).join("");}
async function sha256(bytes:Uint8Array){const copy=new Uint8Array(bytes);return hex(await crypto.subtle.digest("SHA-256",copy.buffer));}
function one(value:any){return Array.isArray(value)?value[0]:value;}

Deno.serve(async(req:Request)=>{
 if(req.method!=="POST")return response({ok:false},405);
 const url=Deno.env.get("SUPABASE_URL"),anon=Deno.env.get("SUPABASE_ANON_KEY"),auth=req.headers.get("Authorization")??"";
 if(!url||!anon||!auth)return response({ok:false},401);
 const db=createClient(url,anon,{global:{headers:{Authorization:auth}},auth:{persistSession:false,autoRefreshToken:false}});
 const {data:userRes,error:userError}=await db.auth.getUser();const user=userRes?.user;if(userError||!user)return response({ok:false},401);
 const {data:canWrite}=await db.rpc("current_user_has_permission",{p_permission:"expose.write"});if(canWrite!==true)return response({ok:false,error:"FORBIDDEN"},403);
 let body:any;try{body=await req.json();}catch{return response({ok:false,error:"INVALID_REQUEST"},400);}
 const exposeId=String(body.expose_id??"");if(!exposeId)return response({ok:false,error:"EXPOSE_REQUIRED"},400);
 const {data:expose,error:exposeError}=await db.from("property_exposes").select("*").eq("id",exposeId).maybeSingle();
 if(exposeError||!expose)return response({ok:false,error:"EXPOSE_NOT_FOUND"},404);
 if(expose.status!=="DRAFT")return expose.storage_path?response({ok:true,expose:{id:expose.id,expose_number:expose.expose_number,version_number:expose.version_number,status:expose.status},reused:true}):response({ok:false,error:"EXPOSE_NOT_DRAFT"},400);
 if(!safeText(expose.title))return response({ok:false,error:"TITLE_REQUIRED"},400);
 const {data:mediaRows,error:mediaError}=await db.from("property_expose_media").select("role,sort_order,property_media!inner(id,media_type,storage_bucket,storage_path,title,alt_text)").eq("expose_id",exposeId).order("sort_order");
 if(mediaError)return response({ok:false,error:"MEDIA_LOAD_FAILED"},500);
 const media=(mediaRows??[]).map((row:any)=>({role:row.role,sort_order:row.sort_order,...one(row.property_media)}));
 const facts:any=expose.facts??{},energy:any=expose.energy??{};
 const pdf=await PDFDocument.create();const serif=await pdf.embedFont(StandardFonts.TimesRoman);const serifBold=await pdf.embedFont(StandardFonts.TimesRomanBold);const sans=await pdf.embedFont(StandardFonts.Helvetica);const sansBold=await pdf.embedFont(StandardFonts.HelveticaBold);
 const pageSize:[number,number]=[595.28,841.89],margin=48,contentWidth=pageSize[0]-margin*2;
 const addFooter=(page:any,pageNo:number)=>{page.drawLine({start:{x:margin,y:35},end:{x:pageSize[0]-margin,y:35},thickness:.5,color:rgb(.75,.76,.74)});page.drawText(`ZeyherMutter · ${safeText(facts.property_number??"")} · Exposé ${expose.version_number} · Seite ${pageNo}`,{x:margin,y:20,size:8,font:sans,color:rgb(.35,.4,.4)});};
 const loadImage=async(item:any)=>{if(!item?.storage_bucket||!item?.storage_path)return null;const {data:blob}=await db.storage.from(item.storage_bucket).download(item.storage_path);if(!blob)return null;try{const bytes=new Uint8Array(await blob.arrayBuffer());if(blob.type==="image/jpeg"||blob.type==="image/jpg")return await pdf.embedJpg(bytes);if(blob.type==="image/png")return await pdf.embedPng(bytes);}catch{}return null;};
 const drawSection=async(title:string,text:unknown,pageNoRef:{value:number})=>{const bodyText=safeText(text);if(!bodyText)return;pageNoRef.value++;let page=pdf.addPage(pageSize);page.drawText(title,{x:margin,y:770,size:24,font:serifBold,color:rgb(.09,.13,.13)});let y=730;for(const line of wrap(bodyText,sans,10.5,contentWidth)){if(y<65){addFooter(page,pageNoRef.value);pageNoRef.value++;page=pdf.addPage(pageSize);y=770;}page.drawText(line,{x:margin,y,size:10.5,font:sans,color:rgb(.22,.28,.28)});y-=16;}addFooter(page,pageNoRef.value);};
 let pageNo={value:1};let page=pdf.addPage(pageSize);page.drawText("ZEYHERMUTTER",{x:margin,y:790,size:10,font:sansBold,color:rgb(.22,.3,.3),characterSpacing:1.5});
 const titleLines=wrap(expose.title,serifBold,26,contentWidth);let titleY=730;for(const line of titleLines.slice(0,3)){page.drawText(line,{x:margin,y:titleY,size:26,font:serifBold,color:rgb(.09,.13,.13)});titleY-=31;}if(expose.subtitle)page.drawText(safeText(expose.subtitle),{x:margin,y:titleY-4,size:14,font:serif,color:rgb(.32,.38,.38),maxWidth:contentWidth});
 const cover=media.find((item:any)=>item.role==="COVER")??media.find((item:any)=>item.media_type==="IMAGE");const coverImage=await loadImage(cover);if(coverImage){const boxW=contentWidth,boxH=285,scale=Math.min(boxW/coverImage.width,boxH/coverImage.height);const w=coverImage.width*scale,h=coverImage.height*scale;page.drawImage(coverImage,{x:margin+(boxW-w)/2,y:345+(boxH-h)/2,width:w,height:h});}
 page.drawText(money(expose.price),{x:margin,y:315,size:20,font:sansBold,color:rgb(.09,.13,.13)});const address=facts.address??{};const location=safeText([address.street&&address.house_number?`${address.street} ${address.house_number}`:null,address.postal_code,address.city,address.district].filter(Boolean).join(" · ")||"Lage auf Anfrage");page.drawText(location,{x:margin,y:289,size:10.5,font:sans,color:rgb(.35,.4,.4),maxWidth:contentWidth});
 const factLine=[`Wohnfläche: ${num(facts.living_area_sqm," m²")}`,`Zimmer: ${num(facts.rooms)}`,`Grundstück: ${num(facts.plot_area_sqm," m²")}`,`Baujahr: ${facts.year_built??"-"}`];page.drawText(factLine.join("   |   "),{x:margin,y:260,size:9.3,font:sans,color:rgb(.2,.27,.27),maxWidth:contentWidth});if(expose.short_description){let y=225;for(const line of wrap(expose.short_description,sans,10.2,contentWidth).slice(0,7)){page.drawText(line,{x:margin,y,size:10.2,font:sans,color:rgb(.27,.32,.32)});y-=15;}}addFooter(page,pageNo.value);
 await drawSection("Objektbeschreibung",expose.long_description,pageNo);await drawSection("Lage",expose.location_description,pageNo);await drawSection("Ausstattung",expose.features_description,pageNo);await drawSection("Sonstige Angaben",expose.other_information,pageNo);
 pageNo.value++;page=pdf.addPage(pageSize);page.drawText("Eckdaten",{x:margin,y:770,size:24,font:serifBold,color:rgb(.09,.13,.13)});let y=725;const rows=[['Objektart',facts.property_type],['Transaktion',facts.transaction_type==='RENT'?'Vermietung':'Verkauf'],['Wohnfläche',facts.living_area_sqm?`${facts.living_area_sqm} m²`:null],['Nutzfläche',facts.usable_area_sqm?`${facts.usable_area_sqm} m²`:null],['Grundstück',facts.plot_area_sqm?`${facts.plot_area_sqm} m²`:null],['Zimmer',facts.rooms],['Schlafzimmer',facts.bedrooms],['Bäder',facts.bathrooms],['Etage',facts.floor],['Baujahr',facts.year_built],['Modernisierung',facts.modernization_year],['Zustand',facts.condition],['Verfügbar ab',facts.available_from],['Stellplätze',facts.parking_spaces]];for(const [label,value] of rows){if(value==null||value==='')continue;page.drawText(safeText(String(label)),{x:margin,y,size:9.5,font:sansBold,color:rgb(.24,.3,.3)});page.drawText(safeText(String(value)),{x:220,y,size:9.5,font:sans,color:rgb(.24,.3,.3)});y-=18;}if(Array.isArray(facts.features)&&facts.features.length){y-=16;page.drawText("Ausstattungsmerkmale",{x:margin,y,size:14,font:serifBold,color:rgb(.09,.13,.13)});y-=24;for(const feature of facts.features.slice(0,20)){const value=feature.type==='BOOLEAN'?(feature.value===true?'Ja':null):feature.value;if(value==null)continue;const label=feature.type==='BOOLEAN'?safeText(feature.label):`${safeText(feature.label)}: ${safeText(value)}${feature.unit?` ${safeText(feature.unit)}`:''}`;if(y<70)break;page.drawText(label,{x:margin,y,size:9.2,font:sans,color:rgb(.3,.35,.35)});y-=14;}}addFooter(page,pageNo.value);
 const gallery=media.filter((item:any)=>item.role==="GALLERY").slice(0,10);for(let i=0;i<gallery.length;i+=2){pageNo.value++;page=pdf.addPage(pageSize);page.drawText("Impressionen",{x:margin,y:790,size:22,font:serifBold,color:rgb(.09,.13,.13)});for(let j=0;j<2;j++){const item=gallery[i+j];if(!item)continue;const image=await loadImage(item);if(!image)continue;const boxW=contentWidth,boxH=315,top=740-j*350,scale=Math.min(boxW/image.width,boxH/image.height);const w=image.width*scale,h=image.height*scale;page.drawImage(image,{x:margin+(boxW-w)/2,y:top-boxH+(boxH-h)/2,width:w,height:h});if(item.title)page.drawText(safeText(item.title),{x:margin,y:top-boxH-16,size:8.5,font:sans,color:rgb(.38,.43,.43)});}addFooter(page,pageNo.value);}
 const plans=media.filter((item:any)=>item.role==="FLOOR_PLAN").slice(0,6);for(const item of plans){pageNo.value++;page=pdf.addPage(pageSize);page.drawText("Grundriss",{x:margin,y:790,size:22,font:serifBold,color:rgb(.09,.13,.13)});const image=await loadImage(item);if(image){const boxW=contentWidth,boxH=650,scale=Math.min(boxW/image.width,boxH/image.height);const w=image.width*scale,h=image.height*scale;page.drawImage(image,{x:margin+(boxW-w)/2,y:90+(boxH-h)/2,width:w,height:h});}if(item.title)page.drawText(safeText(item.title),{x:margin,y:65,size:8.5,font:sans,color:rgb(.38,.43,.43)});addFooter(page,pageNo.value);}
 pageNo.value++;page=pdf.addPage(pageSize);page.drawText("Energie & Datenstand",{x:margin,y:770,size:24,font:serifBold,color:rgb(.09,.13,.13)});y=725;const energyRows=[['Energieausweis vorhanden',energy.certificate_present===true?'Ja':energy.certificate_present===false?'Nein':null],['Ausweistyp',energy.certificate_type],['Energiekennwert',energy.energy_value_kwh?`${energy.energy_value_kwh} kWh/(m²·a)`:null],['Effizienzklasse',energy.efficiency_class],['Energieträger',energy.energy_source],['Gebäudebaujahr',energy.building_year],['Gültig bis',energy.valid_until]];for(const [label,value] of energyRows){if(value==null||value==='')continue;page.drawText(safeText(String(label)),{x:margin,y,size:9.5,font:sansBold,color:rgb(.24,.3,.3)});page.drawText(safeText(String(value)),{x:220,y,size:9.5,font:sans,color:rgb(.24,.3,.3)});y-=18;}y-=28;for(const line of wrap("Dieses Exposé bildet den im CRM für diese Exposé-Version gespeicherten Datenstand zum Zeitpunkt der PDF-Erzeugung ab.",sans,9.5,contentWidth)){page.drawText(line,{x:margin,y,size:9.5,font:sans,color:rgb(.38,.43,.43)});y-=15;}addFooter(page,pageNo.value);
 const pdfBytes=await pdf.save({useObjectStreams:false});const digest=await sha256(pdfBytes);const path=`properties/${expose.property_id}/exposes/${expose.id}-v${expose.version_number}.pdf`,filename=`Expose-${safeText(facts.property_number??expose.expose_number)}-V${expose.version_number}.pdf`;
 const {error:uploadError}=await db.storage.from(BUCKET).upload(path,new Blob([pdfBytes],{type:"application/pdf"}),{contentType:"application/pdf",upsert:false});if(uploadError)return response({ok:false,error:"UPLOAD_FAILED"},500);
 const {data:updated,error:updateError}=await db.from("property_exposes").update({status:"GENERATED",generator_version:GENERATOR_VERSION,storage_bucket:BUCKET,storage_path:path,original_filename:filename,mime_type:"application/pdf",file_size_bytes:pdfBytes.byteLength,sha256:digest,generated_at:new Date().toISOString(),generated_by:user.id}).eq("id",expose.id).eq("status","DRAFT").eq("version",expose.version).select("id,expose_number,version_number,status,version").maybeSingle();
 if(updateError||!updated){await db.storage.from(BUCKET).remove([path]);return response({ok:false,error:updateError?.message?.includes('EXPOSE_')?updateError.message:"CONCURRENT_UPDATE"},409);}
 return response({ok:true,expose:updated});
});
