import { data, Form, Link, redirect, useActionData, useLoaderData } from "react-router";
import type { Route } from "./+types/commission-detail";
import { CommissionFields, type CommissionOfferOption, type CommissionPartyOption } from "~/components/commission-fields";
import { requirePermission } from "~/lib/auth.server";

type ActionResult={error?:string;ok?:string};
const STATUS:Record<string,string>={DRAFT:"Entwurf",EXPECTED:"Erwartet",DUE:"Fällig",INVOICED:"Abgerechnet",PARTIALLY_PAID:"Teilweise bezahlt",PAID:"Bezahlt",CANCELLED:"Storniert"};
const STATUS_CLASS:Record<string,string>={DRAFT:"status-draft",EXPECTED:"status-valuation",DUE:"status-contract-pending",INVOICED:"status-marketing",PARTIALLY_PAID:"status-preparation",PAID:"status-sold",CANCELLED:"status-lost"};
const INVOICE_STATUS:Record<string,string>={NOT_ISSUED:"Noch nicht abgerechnet",ISSUED:"Abgerechnet",CANCELLED:"Storniert"};
const PAYMENT_STATUS:Record<string,string>={OPEN:"Offen",PARTIALLY_PAID:"Teilweise bezahlt",PAID:"Bezahlt"};
function one(value:any){return Array.isArray(value)?value[0]:value;}
function text(fd:FormData,key:string){return String(fd.get(key)??"").trim();}
function decimal(fd:FormData,key:string){const raw=text(fd,key).replace(",",".");if(!raw)return null;const value=Number(raw);return Number.isFinite(value)?value:NaN;}
function money(value:number|string|null|undefined){const n=Number(value);return Number.isFinite(n)?new Intl.NumberFormat("de-DE",{style:"currency",currency:"EUR",maximumFractionDigits:2}).format(n):"—";}
function formatDate(value:string|null){if(!value)return"—";return new Intl.DateTimeFormat("de-DE",{dateStyle:"medium",timeZone:"Europe/Berlin"}).format(new Date(value));}
function target(row:any){const n=Number(row.actual_amount??row.expected_amount);return Number.isFinite(n)?n:0;}
function errorMessage(error:any){const message=String(error?.message??"");if(message.includes("INVALID_COMMISSION_STATUS_TRANSITION"))return"Dieser Provisionsstatus kann aus dem aktuellen Stand nicht gewählt werden.";if(message.includes("COMMISSION_PARTY_REQUIRED"))return"Vor diesem Status muss eine zahlende Partei ausgewählt werden.";if(message.includes("COMMISSION_PERCENT_TERMS_REQUIRED"))return"Für die prozentuale Provision werden Berechnungsgrundlage und Prozentsatz benötigt.";if(message.includes("COMMISSION_FIXED_AMOUNT_REQUIRED"))return"Für die Festprovision wird ein positiver Festbetrag benötigt.";if(message.includes("COMMISSION_DUE_DATE_REQUIRED"))return"Für diesen Status muss eine Fälligkeit hinterlegt sein.";if(message.includes("COMMISSION_TARGET_AMOUNT_REQUIRED"))return"Für diesen Status muss eine erwartete oder tatsächliche Provision vorhanden sein.";if(message.includes("COMMISSION_PARTIAL_PAYMENT_INVALID"))return"Die Teilzahlung muss größer als 0 € und kleiner als die maßgebliche Provision sein.";if(message.includes("COMMISSION_FULL_PAYMENT_INCOMPLETE"))return"Für „Bezahlt“ muss der dokumentierte Zahlbetrag mindestens der maßgeblichen Provision entsprechen.";if(message.includes("COMMISSION_PAID_AT_REQUIRED"))return"Für „Bezahlt“ ist das Zahlungsdatum erforderlich.";if(message.includes("COMMISSION_SELLER_MUST_BE_PROPERTY_OWNER"))return"Für eine Innenprovision muss die zahlende Partei als Eigentümer dieser Immobilie hinterlegt sein.";if(message.includes("COMMISSION_BUYER_REQUIRES_PROPERTY_OFFER"))return"Für eine Außenprovision muss für die zahlende Partei ein Kaufangebot zu dieser Immobilie vorliegen.";if(message.includes("COMMISSION_BUYER_OFFER_CONTACT_MISMATCH"))return"Käufer und ausgewähltes Kaufangebot passen nicht zusammen.";if(message.includes("COMMISSION_OFFER_PROPERTY_MISMATCH"))return"Das ausgewählte Kaufangebot gehört nicht zu dieser Immobilie.";if(message.includes("ARCHIVED_COMMISSION_IMMUTABLE"))return"Eine archivierte Provision kann nicht bearbeitet werden. Bitte zuerst wiederherstellen.";if(message.includes("COMMISSION_RESPONSIBLE_USER_INACTIVE"))return"Der ausgewählte Verantwortliche ist nicht aktiv.";return"Provision konnte nicht aktualisiert werden.";}

async function loadOptions(supabase:any){
 const [{data:properties,error:propertyError},{data:owners,error:ownerError},{data:offers,error:offerError},{data:profiles,error:profileError}]=await Promise.all([
  supabase.from("properties").select("id,property_number,internal_title,purchase_price,status").eq("transaction_type","SALE").order("updated_at",{ascending:false}).limit(500),
  supabase.from("property_owners").select("property_id,contact_id,contacts(id,contact_number,first_name,last_name,archived_at)").limit(1000),
  supabase.from("purchase_offers").select("id,offer_number,property_id,contact_id,amount,status,archived_at,contacts(id,contact_number,first_name,last_name,archived_at)").is("archived_at",null).in("status",["DRAFT","SUBMITTED","COUNTERED","ACCEPTED"]).order("updated_at",{ascending:false}).limit(1000),
  supabase.from("profiles").select("user_id,display_name").eq("status","ACTIVE").order("display_name"),
 ]);
 if(propertyError||ownerError||offerError||profileError)throw new Response("Provisionsoptionen konnten nicht geladen werden.",{status:500});
 const propertyIds=new Set((properties??[]).map((p:any)=>p.id));const partyOptions:CommissionPartyOption[]=[];const seen=new Set<string>();
 for(const owner of owners??[]){const contact=one(owner.contacts);if(!propertyIds.has(owner.property_id)||!contact||contact.archived_at)continue;const key=`SELLER:${owner.property_id}:${owner.contact_id}`;if(seen.has(key))continue;seen.add(key);partyOptions.push({propertyId:owner.property_id,contactId:owner.contact_id,side:"SELLER",label:`${contact.first_name} ${contact.last_name} · ${contact.contact_number}`});}
 const offerOptions:CommissionOfferOption[]=[];
 for(const offer of offers??[]){const contact=one(offer.contacts);if(!propertyIds.has(offer.property_id)||!contact||contact.archived_at)continue;const key=`BUYER:${offer.property_id}:${offer.contact_id}`;if(!seen.has(key)){seen.add(key);partyOptions.push({propertyId:offer.property_id,contactId:offer.contact_id,side:"BUYER",label:`${contact.first_name} ${contact.last_name} · ${contact.contact_number}`});}offerOptions.push({id:offer.id,propertyId:offer.property_id,contactId:offer.contact_id,label:offer.offer_number,amount:offer.amount,status:offer.status});}
 return {properties:properties??[],partyOptions,offers:offerOptions,profiles:profiles??[]};
}

export async function loader({request,context,params}:Route.LoaderArgs){
 const {supabase,responseHeaders,profile}=await requirePermission(request,context.cloudflare.env,"commission.read");const id=params.commissionId!;
 const {data:row,error}=await supabase.from("commissions").select("*,properties(id,property_number,internal_title,status,purchase_price),party:contacts!commissions_party_contact_id_fkey(id,contact_number,first_name,last_name),purchase_offers(id,offer_number,amount,status,contact_id)").eq("id",id).maybeSingle();
 if(error||!row)throw new Response("Provision nicht gefunden.",{status:404,headers:responseHeaders()});
 const [options,{data:transitions},{data:canWrite},{data:canArchive},{data:canAudit}]=await Promise.all([loadOptions(supabase),supabase.from("commission_status_transitions").select("to_status,description").eq("from_status",row.status).order("to_status"),supabase.rpc("current_user_has_permission",{p_permission:"commission.write"}),supabase.rpc("current_user_has_permission",{p_permission:"commission.archive"}),supabase.rpc("current_user_has_permission",{p_permission:"audit.read"})]);
 let audit:any[]=[];if(canAudit===true){const result=await supabase.from("audit_events").select("id,occurred_at,actor_display_name_snapshot,action,field_changes").eq("entity_type","COMMISSION").eq("entity_id",id).order("occurred_at",{ascending:false}).limit(80);if(!result.error)audit=result.data??[];}
 return data({row,profile,transitions:transitions??[],canWrite:canWrite===true,canArchive:canArchive===true,audit,...options},{headers:responseHeaders()});
}

export async function action({request,context,params}:Route.ActionArgs){
 const {supabase,responseHeaders}=await requirePermission(request,context.cloudflare.env,"commission.write");const id=params.commissionId!,fd=await request.formData(),intent=text(fd,"_intent");
 const version=Number(text(fd,"version"));if(!Number.isInteger(version)||version<1)return data<ActionResult>({error:"Ungültige Datensatzversion."},{status:400,headers:responseHeaders()});
 const conflict=()=>data<ActionResult>({error:"Die Provision wurde zwischenzeitlich geändert. Bitte Seite neu laden."},{status:409,headers:responseHeaders()});
 if(intent==="update"){
   const method=text(fd,"calculation_method"),basis=decimal(fd,"calculation_basis"),percent=decimal(fd,"agreed_percent"),fixed=decimal(fd,"agreed_fixed_amount"),actual=decimal(fd,"actual_amount");
   for(const [value,label] of [[basis,"Berechnungsgrundlage"],[percent,"Prozentsatz"],[fixed,"Festbetrag"],[actual,"tatsächliche Provision"]] as const){if(typeof value==="number"&&(!Number.isFinite(value)||value<0))return data<ActionResult>({error:`${label} muss eine gültige, nicht negative Zahl sein.`},{status:400,headers:responseHeaders()});}
   if(percent!==null&&percent>100)return data<ActionResult>({error:"Der Prozentsatz darf 100 % nicht überschreiten."},{status:400,headers:responseHeaders()});
   const update:any={property_id:text(fd,"property_id"),purchase_offer_id:text(fd,"purchase_offer_id")||null,party_contact_id:text(fd,"party_contact_id")||null,side:text(fd,"side"),calculation_method:method,calculation_basis:basis,agreed_percent:method==="PERCENT"?percent:null,agreed_fixed_amount:method==="FIXED"?fixed:null,actual_amount:actual,due_date:text(fd,"due_date")||null,invoice_reference:text(fd,"invoice_reference")||null,primary_responsible_user:text(fd,"primary_responsible_user"),internal_notes:text(fd,"internal_notes")||null};
   if(fd.has("paid_amount"))update.paid_amount=decimal(fd,"paid_amount")??0;if(fd.has("paid_at"))update.paid_at=text(fd,"paid_at")||null;
   const {data:updated,error}=await supabase.from("commissions").update(update).eq("id",id).eq("version",version).select("id").maybeSingle();if(error)return data<ActionResult>({error:errorMessage(error)},{status:400,headers:responseHeaders()});if(!updated)return conflict();return redirect(`/commissions/${id}`,{headers:responseHeaders()});
 }
 if(intent==="status"){
   const next=text(fd,"target_status"),update:any={status:next};if(fd.has("invoice_reference"))update.invoice_reference=text(fd,"invoice_reference")||null;if(fd.has("paid_amount")){const amount=decimal(fd,"paid_amount");if(amount===null||!Number.isFinite(amount)||amount<0)return data<ActionResult>({error:"Bitte einen gültigen Zahlbetrag angeben."},{status:400,headers:responseHeaders()});update.paid_amount=amount;}if(fd.has("paid_at"))update.paid_at=text(fd,"paid_at")||null;
   const {data:updated,error}=await supabase.from("commissions").update(update).eq("id",id).eq("version",version).select("id").maybeSingle();if(error)return data<ActionResult>({error:errorMessage(error)},{status:400,headers:responseHeaders()});if(!updated)return conflict();return redirect(`/commissions/${id}#status`,{headers:responseHeaders()});
 }
 if(intent==="archive"||intent==="restore"){
   await requirePermission(request,context.cloudflare.env,"commission.archive");const {data:updated,error}=await supabase.from("commissions").update({archived_at:intent==="archive"?new Date().toISOString():null}).eq("id",id).eq("version",version).select("id").maybeSingle();if(error)return data<ActionResult>({error:errorMessage(error)},{status:400,headers:responseHeaders()});if(!updated)return conflict();return redirect(`/commissions/${id}`,{headers:responseHeaders()});
 }
 return data<ActionResult>({error:"Unbekannte Aktion."},{status:400,headers:responseHeaders()});
}

function auditLabel(changes:any){if(!changes||typeof changes!=="object")return"Änderung dokumentiert";const keys=Object.keys(changes);if(keys.includes("record"))return"Provisionsvorgang angelegt";return keys.map((key)=>({status:"Status",property_id:"Immobilie",party_contact_id:"Partei",side:"Provisionsseite",calculation_method:"Berechnungsart",calculation_basis:"Berechnungsgrundlage",agreed_percent:"Prozentsatz",agreed_fixed_amount:"Festbetrag",actual_amount:"Tatsächliche Provision",due_date:"Fälligkeit",invoice_reference:"Rechnungsreferenz",paid_amount:"Bezahlter Betrag",paid_at:"Zahlungsdatum",primary_responsible_user:"Verantwortlich",internal_notes:"Notizen",archived_at:"Archiv"}[key]??key)).join(", ");}

export default function CommissionDetail(){
 const {row,profile,transitions,canWrite,canArchive,audit,properties,partyOptions,offers,profiles}=useLoaderData<typeof loader>();const result=useActionData<typeof action>();const property=one(row.properties),party=one(row.party),offer=one(row.purchase_offers),targetAmount=target(row),locked=Boolean(row.archived_at);
 return <main className="editor-shell"><header className="editor-header"><div><Link className="back-link" to="/commissions">← Provisionen</Link><p className="eyebrow">{row.commission_number} · {row.side==="SELLER"?"Innenprovision":"Außenprovision"}</p><div className="property-title-row"><h1 className="editor-title">{property?.property_number??"Provision"}</h1><span className={`status-pill ${STATUS_CLASS[row.status]??"status-draft"}`}>{locked?"Archiviert":STATUS[row.status]??row.status}</span></div><p className="editor-meta">{property?.internal_title??"—"} · Version {row.version}</p></div><div className="header-actions"><Link className="secondary-button link-button" to={`/properties/${row.property_id}`}>Immobilie öffnen</Link>{canArchive?<Form method="post"><input type="hidden" name="_intent" value={locked?"restore":"archive"}/><input type="hidden" name="version" value={row.version}/><button className="secondary-button" type="submit">{locked?"Wiederherstellen":"Archivieren"}</button></Form>:null}<span className="badge">{__APP_ENV_LABEL__}</span><small>{profile.display_name}</small></div></header>
 {result?.error?<div className="form-error">{result.error}</div>:null}
 <div className="property-summary-grid">
  <section className="data-card"><div className="card-head"><div><p className="eyebrow">Provisionsseite</p><h2>{row.side==="SELLER"?"Innenprovision":"Außenprovision"}</h2></div></div><p><strong>{party?`${party.first_name} ${party.last_name}`:"Partei noch offen"}</strong></p><p className="subtle">{party?.contact_number??(row.side==="SELLER"?"Eigentümerseite":"Käuferseite")}{offer?.offer_number?` · ${offer.offer_number}`:""}</p></section>
  <section className="data-card"><div className="card-head"><div><p className="eyebrow">Betrag</p><h2>{money(row.actual_amount??row.expected_amount)}</h2></div></div><p className="subtle">Erwartet {money(row.expected_amount)}{row.actual_amount!==null?` · tatsächlich ${money(row.actual_amount)}`:""}</p><p className="subtle">Bezahlt {money(row.paid_amount)} · offen {money(Math.max(0,targetAmount-Number(row.paid_amount??0)))}</p></section>
  <section className="data-card"><div className="card-head"><div><p className="eyebrow">Abrechnung & Zahlung</p><h2>{PAYMENT_STATUS[row.payment_status]??row.payment_status}</h2></div></div><p className="subtle">{INVOICE_STATUS[row.invoice_status]??row.invoice_status} · Fälligkeit {formatDate(row.due_date)}</p><p className="subtle">{row.invoice_reference?`Referenz ${row.invoice_reference}`:"Keine Rechnungsreferenz"}{row.paid_at?` · bezahlt ${formatDate(row.paid_at)}`:""}</p></section>
 </div>

 <section className="data-card" id="status"><div className="card-head"><div><p className="eyebrow">Workflow</p><h2>Status & nächste Schritte</h2></div><span className={`status-pill ${STATUS_CLASS[row.status]??"status-draft"}`}>{STATUS[row.status]??row.status}</span></div>{locked?<p className="empty-state">Archivierte Provisionen können erst nach dem Wiederherstellen weiterbearbeitet werden.</p>:canWrite?<div className="commission-transition-list">{transitions.map((transition:any)=>{
   if(transition.to_status==="INVOICED")return <Form method="post" className="inline-actions" key={transition.to_status}><input type="hidden" name="_intent" value="status"/><input type="hidden" name="version" value={row.version}/><input type="hidden" name="target_status" value={transition.to_status}/><input name="invoice_reference" defaultValue={row.invoice_reference??""} placeholder="Rechnungsreferenz · optional"/><button className="secondary-button" type="submit">→ {STATUS[transition.to_status]}</button></Form>;
   if(transition.to_status==="PARTIALLY_PAID")return <Form method="post" className="inline-actions" key={transition.to_status}><input type="hidden" name="_intent" value="status"/><input type="hidden" name="version" value={row.version}/><input type="hidden" name="target_status" value={transition.to_status}/><input name="paid_amount" type="number" min="0.01" step="0.01" placeholder="Teilzahlung €" required/><button className="secondary-button" type="submit">→ {STATUS[transition.to_status]}</button></Form>;
   if(transition.to_status==="PAID")return <Form method="post" className="inline-actions" key={transition.to_status}><input type="hidden" name="_intent" value="status"/><input type="hidden" name="version" value={row.version}/><input type="hidden" name="target_status" value={transition.to_status}/><input name="paid_amount" type="number" min="0.01" step="0.01" defaultValue={Math.max(Number(row.paid_amount??0),targetAmount)||""} required/><input name="paid_at" type="date" required/><button className="primary-button" type="submit">→ {STATUS[transition.to_status]}</button></Form>;
   return <Form method="post" key={transition.to_status}><input type="hidden" name="_intent" value="status"/><input type="hidden" name="version" value={row.version}/><input type="hidden" name="target_status" value={transition.to_status}/><button className="secondary-button" type="submit" title={transition.description??""}>→ {STATUS[transition.to_status]??transition.to_status}</button></Form>;
 })}{transitions.length===0?<p className="empty-state">Für diesen Status ist aktuell kein weiterer Statuswechsel vorgesehen.</p>:null}</div>:<p className="empty-state">Keine Berechtigung zum Bearbeiten von Provisionen.</p>}</section>

 <section className="editor-card"><div className="card-head"><div><p className="eyebrow">Provisionsakte</p><h2>Vereinbarung & Beträge</h2></div><span className="subtle">Erwartungswert wird bei Prozentangabe automatisch berechnet.</span></div><Form method="post"><input type="hidden" name="_intent" value="update"/><input type="hidden" name="version" value={row.version}/><CommissionFields properties={properties} partyOptions={partyOptions} offers={offers} profiles={profiles} defaultResponsibleUser={row.primary_responsible_user} initial={row} disabled={!canWrite||locked} showPaymentFields={row.status==="PARTIALLY_PAID"||row.status==="PAID"}/>{canWrite&&!locked?<div className="form-actions"><button className="primary-button" type="submit">Provision speichern</button></div>:null}</Form></section>

 <section className="data-card"><div className="card-head"><div><p className="eyebrow">Historie</p><h2>Änderungsverlauf</h2></div><span className="subtle">{audit.length} Einträge</span></div><div className="data-list">{audit.map((event:any)=><div className="data-row" key={event.id}><div><strong>{auditLabel(event.field_changes)}</strong><small>{event.actor_display_name_snapshot??"System"} · {event.action}</small></div><div className="row-meta"><span>{new Intl.DateTimeFormat("de-DE",{dateStyle:"medium",timeStyle:"short",timeZone:"Europe/Berlin"}).format(new Date(event.occurred_at))}</span></div></div>)}{audit.length===0?<p className="empty-state">Keine sichtbare Historie vorhanden.</p>:null}</div></section>
 </main>;
}
