import { data, Form, Link, useActionData, useLoaderData } from "react-router";
import type { Route } from "./+types/inquiry-detail";
import { MentionPicker } from "~/components/mention-picker";
import { TaskModal } from "~/components/task-modal";
import { ConcurrencyConflictModal } from "~/components/concurrency-conflict-modal";
import { requirePermission } from "~/lib/auth.server";
import "~/inquiry.css";

type ActionResult={error?:string;ok?:string};
const STATUS:Record<string,string>={NEW:"Neu",CONTACTED:"Kontaktiert",QUALIFIED:"Qualifiziert",VIEWING_PLANNED:"Besichtigung geplant",CLOSED:"Erledigt",LOST:"Kein weiteres Interesse"};
const CHANNEL:Record<string,string>={WEBSITE:"Website",PORTAL:"Immobilienportal",PHONE:"Telefon",EMAIL:"E-Mail",REFERRAL:"Empfehlung",WALK_IN:"Persönlich",OTHER:"Sonstige"};
const TASK_STATUS:Record<string,string>={OPEN:"Offen",IN_PROGRESS:"In Bearbeitung",DONE:"Erledigt",CANCELLED:"Abgebrochen"};
const VIEWING_STATUS:Record<string,string>={PLANNED:"Geplant",CONFIRMED:"Bestätigt",COMPLETED:"Durchgeführt",CANCELLED:"Abgesagt",NO_SHOW:"Nicht erschienen"};
const MAIN_FLOW=["NEW","CONTACTED","QUALIFIED","VIEWING_PLANNED","CLOSED"];
function one(v:any){return Array.isArray(v)?v[0]:v;}function text(fd:FormData,k:string){return String(fd.get(k)??"").trim();}
function formatDate(v:string|null){if(!v)return "—";return new Intl.DateTimeFormat("de-DE",{dateStyle:"medium",timeStyle:"short",timeZone:"Europe/Berlin"}).format(new Date(v));}
function berlinLocalToIso(value:string){if(!value)return null;const m=value.match(/^(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2})$/);if(!m)return null;const target=Date.UTC(+m[1],+m[2]-1,+m[3],+m[4],+m[5]);let guess=target;for(let i=0;i<2;i++){const parts=new Intl.DateTimeFormat("en-CA",{timeZone:"Europe/Berlin",year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hourCycle:"h23"}).formatToParts(new Date(guess));const g=(t:string)=>Number(parts.find(p=>p.type===t)?.value);const rendered=Date.UTC(g("year"),g("month")-1,g("day"),g("hour"),g("minute"));guess=target-(rendered-guess);}return new Date(guess).toISOString();}
export async function loader({request,context,params}:Route.LoaderArgs){
 const {supabase,responseHeaders,profile}=await requirePermission(request,context.cloudflare.env,"inquiry.read");const id=params.inquiryId!,url=new URL(request.url);
 const [{data:row,error},{data:profiles},{data:properties},{data:searchProfiles},{data:transitions},{data:comments},{data:activity},{data:audit},{data:tasks},{data:viewings},{data:canWrite},{data:canArchive}]=await Promise.all([
  supabase.from("inquiries").select("*,contacts!inner(id,contact_number,first_name,last_name,email,phone,mobile),properties(id,property_number,internal_title),search_profiles(id,search_profile_number,title,contact_id,status,transaction_type)").eq("id",id).single(),
  supabase.from("profiles").select("user_id,display_name,status").eq("status","ACTIVE").order("display_name"),
  supabase.from("properties").select("id,property_number,internal_title,status").neq("status","ARCHIVED").order("updated_at",{ascending:false}).limit(500),
  supabase.from("search_profiles").select("id,search_profile_number,title,contact_id,status,transaction_type").is("archived_at",null).order("updated_at",{ascending:false}).limit(1000),
  supabase.from("inquiry_status_transitions").select("from_status,to_status,description"),
  supabase.from("comments").select("id,body,author_user_id,created_at").eq("entity_type","INQUIRY").eq("entity_id",id).is("archived_at",null).order("created_at",{ascending:false}).limit(100),
  supabase.from("activity_events").select("id,activity_type,title,description,actor_user_id,occurred_at").eq("inquiry_id",id).order("occurred_at",{ascending:false}).limit(100),
  supabase.from("audit_events").select("id,occurred_at,actor_display_name_snapshot,action,field_changes,description").eq("entity_type","INQUIRY").eq("entity_id",id).order("occurred_at",{ascending:false}).limit(100),
  supabase.from("tasks").select("id,task_number,title,description,status,priority,due_at,responsible_user,version").eq("inquiry_id",id).is("archived_at",null).order("due_at",{ascending:true}).limit(100),
  supabase.from("viewings").select("id,viewing_number,status,starts_at,meeting_point,properties(property_number,internal_title),search_profiles(search_profile_number,title)").eq("inquiry_id",id).is("archived_at",null).order("starts_at",{ascending:false}).limit(100),
  supabase.rpc("current_user_has_permission",{p_permission:"inquiry.write"}),supabase.rpc("current_user_has_permission",{p_permission:"inquiry.archive"})
 ]);
 if(error||!row)throw new Response("Anfrage nicht gefunden.",{status:404});
 return data({row,profiles:profiles??[],properties:properties??[],searchProfiles:searchProfiles??[],transitions:transitions??[],comments:comments??[],activity:activity??[],audit:audit??[],tasks:tasks??[],viewings:viewings??[],profile,canWrite:canWrite===true,canArchive:canArchive===true,searchProfileCreated:url.searchParams.get("searchProfileCreated")==="1"},{headers:responseHeaders()});
}
export async function action({request,context,params}:Route.ActionArgs){
 const {supabase,responseHeaders,userId}=await requirePermission(request,context.cloudflare.env,"inquiry.write");const fd=await request.formData(),intent=text(fd,"_intent"),id=params.inquiryId!;
 if(intent==="update"){const expected=Number(text(fd,"version")),contactId=text(fd,"contact_id"),spId=text(fd,"search_profile_id")||null;if(spId){const {data:sp}=await supabase.from("search_profiles").select("id,contact_id").eq("id",spId).maybeSingle();if(!sp||sp.contact_id!==contactId)return data<ActionResult>({error:"Das Suchprofil gehört nicht zum ausgewählten Kontakt."},{status:400,headers:responseHeaders()});}const {data:updated,error}=await supabase.from("inquiries").update({contact_id:contactId,property_id:text(fd,"property_id")||null,search_profile_id:spId,channel:text(fd,"channel")||"OTHER",source_label:text(fd,"source_label")||null,message:text(fd,"message")||null,primary_responsible_user:text(fd,"primary_responsible_user")||userId}).eq("id",id).eq("version",expected).select("id").maybeSingle();if(error)return data<ActionResult>({error:"Anfrage konnte nicht gespeichert werden."},{status:400,headers:responseHeaders()});if(!updated)return data<ActionResult>({error:"Die Anfrage wurde inzwischen geändert. Bitte neu laden."},{status:409,headers:responseHeaders()});return data<ActionResult>({ok:"Anfrage gespeichert."},{headers:responseHeaders()});}
 if(intent==="status"){const expected=Number(text(fd,"version")),next=text(fd,"status"),lostReason=text(fd,"lost_reason")||null;const {data:updated,error}=await supabase.from("inquiries").update({status:next,lost_reason:lostReason}).eq("id",id).eq("version",expected).select("id").maybeSingle();if(error){const msg=String(error.message??"");if(msg.includes("INQUIRY_PROPERTY_REQUIRED_FOR_CLOSE"))return data<ActionResult>({error:"Diese objektbezogene Anfrage kann erst als erledigt markiert werden, wenn eine Immobilie verknüpft ist."},{status:400,headers:responseHeaders()});return data<ActionResult>({error:next==="LOST"?"Für „Kein weiteres Interesse“ ist ein Grund erforderlich.":"Dieser Statuswechsel ist fachlich nicht erlaubt."},{status:400,headers:responseHeaders()});}if(!updated)return data<ActionResult>({error:"Die Anfrage wurde inzwischen geändert."},{status:409,headers:responseHeaders()});return data<ActionResult>({ok:`Status: ${STATUS[next]??next}`},{headers:responseHeaders()});}
 if(intent==="archive"||intent==="restore"){const expected=Number(text(fd,"version"));const {data:updated,error}=await supabase.from("inquiries").update({archived_at:intent==="archive"?new Date().toISOString():null}).eq("id",id).eq("version",expected).select("id").maybeSingle();if(error)return data<ActionResult>({error:"Archivstatus konnte nicht geändert werden."},{status:403,headers:responseHeaders()});if(!updated)return data<ActionResult>({error:"Die Anfrage wurde inzwischen geändert."},{status:409,headers:responseHeaders()});return data<ActionResult>({ok:intent==="archive"?"Anfrage archiviert.":"Anfrage wiederhergestellt."},{headers:responseHeaders()});}
 if(intent==="task"){const due=berlinLocalToIso(text(fd,"due_at"));if(!text(fd,"task_title")||!due)return data<ActionResult>({error:"Aufgabe benötigt Titel sowie gültiges Datum/Uhrzeit."},{status:400,headers:responseHeaders()});const {data:inq}=await supabase.from("inquiries").select("contact_id,property_id,search_profile_id").eq("id",id).single();const {error}=await supabase.from("tasks").insert({title:text(fd,"task_title"),description:text(fd,"task_description")||null,priority:text(fd,"priority")||"NORMAL",due_at:due,responsible_user:text(fd,"responsible_user")||userId,contact_id:inq?.contact_id??null,property_id:inq?.property_id??null,inquiry_id:id,search_profile_id:inq?.search_profile_id??null,created_by:userId,updated_by:userId});if(error)return data<ActionResult>({error:"Aufgabe konnte nicht angelegt werden."},{status:400,headers:responseHeaders()});return data<ActionResult>({ok:"Aufgabe angelegt."},{headers:responseHeaders()});}
 if(intent==="task_status"){const status=text(fd,"task_status"),update:any={status};update.completed_at=status==="DONE"?new Date().toISOString():null;const {data:updated,error}=await supabase.from("tasks").update(update).eq("id",text(fd,"task_id")).eq("inquiry_id",id).eq("version",Number(text(fd,"task_version"))).select("id").maybeSingle();if(error)return data<ActionResult>({error:"Aufgabe konnte nicht aktualisiert werden."},{status:400,headers:responseHeaders()});if(!updated)return data<ActionResult>({error:"Die Aufgabe wurde inzwischen geändert. Bitte neu laden."},{status:409,headers:responseHeaders()});return data<ActionResult>({ok:"Aufgabe aktualisiert."},{headers:responseHeaders()});}
 if(intent==="comment"){const body=text(fd,"body"),mentions=fd.getAll("mention_user_id").map(String);const {error}=await supabase.rpc("create_inquiry_comment",{p_inquiry_id:id,p_body:body,p_mentioned_user_ids:mentions});if(error)return data<ActionResult>({error:"Kommentar konnte nicht gespeichert werden."},{status:400,headers:responseHeaders()});return data<ActionResult>({ok:"Kommentar gespeichert."},{headers:responseHeaders()});}
 return data<ActionResult>({error:"Unbekannte Aktion."},{status:400,headers:responseHeaders()});
}
export default function InquiryDetail(){
 const {row,profiles,properties,searchProfiles,transitions,comments,activity,audit,tasks,viewings,profile,canWrite,canArchive,searchProfileCreated}=useLoaderData<typeof loader>();const result=useActionData<typeof action>();const c=one(row.contacts),p=one(row.properties),sp=one(row.search_profiles),profileMap=Object.fromEntries(profiles.map((x:any)=>[x.user_id,x.display_name]));const conflict=Boolean(result?.error&&result.error.includes("inzwischen geändert"));const generalContact=row.channel==="WEBSITE"&&row.source_label==="ZeyherMutter Website · Kontakt";const next=(transitions as any[]).filter(t=>t.from_status===row.status).filter(t=>!(t.to_status==="CLOSED"&&!row.property_id&&!generalContact));const availableProfiles=searchProfiles.filter((x:any)=>x.contact_id===row.contact_id);
 const viewingUrl=`/viewings/new?contact_id=${row.contact_id}${row.property_id?`&property_id=${row.property_id}`:""}${row.search_profile_id?`&search_profile_id=${row.search_profile_id}`:""}&inquiry_id=${row.id}`;
 return <main className="editor-shell"><header className="editor-header"><div><Link className="back-link" to="/inquiries">← Anfragen</Link><p className="eyebrow">{row.inquiry_number} · Modul 04</p><h1 className="editor-title">Anfrage von {c.first_name} {c.last_name}</h1><p className="editor-meta">{CHANNEL[row.channel]??row.channel} · Eingang {formatDate(row.received_at)}</p></div><div className="header-user"><span className={`inquiry-status ${String(row.status).toLowerCase()}`}>{row.archived_at?"Archiviert":STATUS[row.status]??row.status}</span><span className="badge">STAGING</span><small>{profile.display_name}</small></div></header><div className="inquiry-page">{result?.error&&!conflict?<div className="form-error">{result.error}</div>:null}{result?.ok?<div className="success-banner">{result.ok}</div>:null}{searchProfileCreated?<div className="success-banner">Suchprofil wurde angelegt und direkt mit dieser Anfrage verknüpft.</div>:null}
 <section className="data-card"><div className="card-head"><div><p className="eyebrow">Interessent</p><h2>{c.first_name} {c.last_name}</h2></div><Link className="subtle-link" to={`/crm/contacts/${c.id}`}>Kontakt öffnen →</Link></div><div className="inquiry-summary"><div><span>Kontakt</span><strong>{c.contact_number}</strong></div><div><span>Immobilie</span><strong>{p?.property_number??"—"}</strong></div><div><span>Suchprofil</span><strong>{sp?.search_profile_number??"—"}</strong></div><div><span>Beantwortet</span><strong>{formatDate(row.answered_at)}</strong></div></div><div className="inline-actions" style={{marginTop:14}}>{p?<Link className="secondary-button link-button compact" to={`/properties/${p.id}`}>Immobilie öffnen</Link>:null}{sp?<Link className="secondary-button link-button compact" to={`/search-profiles/${sp.id}`}>Zum Suchprofil →</Link>:<Link className="secondary-button link-button compact" to={`/search-profiles/new?contact_id=${c.id}&inquiry_id=${row.id}`}>Suchprofil anlegen</Link>}<Link className="primary-button link-button compact" to={viewingUrl}>+ Besichtigung anlegen</Link></div></section>
 <section className="data-card"><div className="card-head"><div><p className="eyebrow">Status</p><h2>Anfragefortschritt</h2></div></div><p className="workflow-help">Hier siehst du, in welcher Phase sich die Anfrage befindet und welcher nächste Schritt möglich ist.</p><div className="inquiry-workflow">{MAIN_FLOW.map((s,i)=><span key={s} className={`inquiry-status ${String(s).toLowerCase()}`} style={{opacity:row.status===s?1:.48}}>{i>0?"→ ":""}{STATUS[s]}</span>)}<span className="subtle">Nebenpfad: {STATUS.LOST}</span></div>{canWrite&&!row.archived_at?<div className="inline-actions" style={{justifyContent:"flex-start",marginTop:14}}>{next.map((t:any)=><Form method="post" key={t.to_status} className="inline-actions"><input type="hidden" name="_intent" value="status"/><input type="hidden" name="version" value={row.version}/><input type="hidden" name="status" value={t.to_status}/>{t.to_status==="LOST"?<input name="lost_reason" placeholder="Grund *" required/>:null}<button className="secondary-button compact" type="submit">{t.description??STATUS[t.to_status]}</button></Form>)}</div>:null}{!row.property_id&&!generalContact&&next.some((t:any)=>t.to_status==="CLOSED")?null:!row.property_id&&!generalContact&&row.status!=="CLOSED"?<p className="editor-meta">Für eine objektbezogene Anfrage ist „Erledigt“ erst möglich, sobald eine Immobilie verknüpft wurde.</p>:null}{row.status==="LOST"&&row.lost_reason?<p className="editor-meta">Grund: {row.lost_reason}</p>:null}</section>
 <section className="data-card"><div className="card-head"><div><p className="eyebrow">Besichtigungen</p><h2>{viewings.length} Termine</h2></div><Link className="primary-button link-button compact" to={viewingUrl}>+ Besichtigung anlegen</Link></div><div className="module04-context-list">{viewings.map((v:any)=>{const vp=one(v.properties),vsp=one(v.search_profiles);return <div className="module04-context-row" key={v.id}><div><strong>{formatDate(v.starts_at)} · {vp?.property_number??"Immobilie"}</strong><small>{vp?.internal_title??""}{vsp?.search_profile_number?` · ${vsp.search_profile_number}`:""} · {VIEWING_STATUS[v.status]??v.status}</small></div><Link className="secondary-button link-button compact" to={`/viewings/${v.id}`}>Besichtigung öffnen</Link></div>})}{viewings.length===0?<p className="empty-state">Noch keine Besichtigung zu dieser Anfrage.</p>:null}</div></section>
 <section className="data-card"><div className="card-head"><div><p className="eyebrow">Stammdaten</p><h2>Anfrage bearbeiten</h2></div>{canArchive?<Form method="post"><input type="hidden" name="version" value={row.version}/><button className="secondary-button compact" name="_intent" value={row.archived_at?"restore":"archive"} type="submit">{row.archived_at?"Wiederherstellen":"Archivieren"}</button></Form>:null}</div><Form method="post"><input type="hidden" name="_intent" value="update"/><input type="hidden" name="version" value={row.version}/><fieldset disabled={!canWrite||Boolean(row.archived_at)} style={{border:0,padding:0,margin:0}}><div className="form-grid"><label className="form-field"><span>Kontakt</span><input value={`${c.last_name}, ${c.first_name} · ${c.contact_number}`} readOnly/><input type="hidden" name="contact_id" value={row.contact_id}/></label><label className="form-field"><span>Kanal</span><select name="channel" defaultValue={row.channel}>{Object.entries(CHANNEL).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label className="form-field"><span>Quelle / Portal</span><input name="source_label" defaultValue={row.source_label??""}/></label><label className="form-field"><span>Verantwortlich</span><select name="primary_responsible_user" defaultValue={row.primary_responsible_user??""}><option value="">—</option>{profiles.map((x:any)=><option key={x.user_id} value={x.user_id}>{x.display_name}</option>)}</select></label><label className="form-field"><span>Immobilie</span><select name="property_id" defaultValue={row.property_id??""}><option value="">Keine konkrete Immobilie</option>{properties.map((x:any)=><option key={x.id} value={x.id}>{x.property_number} · {x.internal_title}</option>)}</select></label><label className="form-field"><span>Suchprofil</span><select name="search_profile_id" defaultValue={row.search_profile_id??""}><option value="">Kein Suchprofil</option>{availableProfiles.map((x:any)=><option key={x.id} value={x.id}>{x.search_profile_number} · {x.title} · {x.status==="ACTIVE"?"Aktiv":x.status==="PAUSED"?"Pausiert":"Abgeschlossen"} · {x.transaction_type==="BUY"?"Kauf":"Miete"}</option>)}</select><small>{availableProfiles.length} vorhandene Suchprofile dieses Kontakts. <Link className="subtle-link" to={`/search-profiles/new?contact_id=${c.id}&inquiry_id=${row.id}`}>Neues Suchprofil anlegen</Link></small></label></div><label className="form-field"><span>Nachricht</span><textarea name="message" rows={6} defaultValue={row.message??""}/></label><div className="form-actions"><button className="primary-button" type="submit">Anfrage speichern</button></div></fieldset></Form></section>
 <div className="collaboration-grid"><section className="data-card"><div className="card-head"><div><p className="eyebrow">Wiedervorlage</p><h2>Aufgaben</h2></div><Link className="subtle-link" to="/crm/tasks">Alle Aufgaben</Link></div><div className="data-list">{tasks.map((t:any)=><div className="data-row" key={t.id}><div><strong>{t.title}</strong><small>{t.task_number} · {TASK_STATUS[t.status]??t.status} · {formatDate(t.due_at)}</small></div><TaskModal task={t} responsibleName={profileMap[t.responsible_user]} contextLabel={`${row.inquiry_number} · ${c.first_name} ${c.last_name}`} contextHref={`/inquiries/${row.id}`} canWrite={canWrite}/></div>)}{tasks.length===0?<p className="empty-state">Keine Aufgaben.</p>:null}</div>{canWrite&&!row.archived_at?<Form method="post" className="auth-form"><input type="hidden" name="_intent" value="task"/><label><span>Titel *</span><input name="task_title" required/></label><label><span>Beschreibung</span><textarea name="task_description" rows={3}/></label><label><span>Fällig *</span><input name="due_at" type="datetime-local" required/></label><label><span>Priorität</span><select name="priority" defaultValue="NORMAL"><option value="LOW">Niedrig</option><option value="NORMAL">Normal</option><option value="HIGH">Hoch</option><option value="URGENT">Dringend</option></select></label><label><span>Verantwortlich</span><select name="responsible_user" defaultValue={profile.user_id}>{profiles.map((x:any)=><option key={x.user_id} value={x.user_id}>{x.display_name}</option>)}</select></label><button className="secondary-button" type="submit">Aufgabe anlegen</button></Form>:null}</section><section className="data-card"><div className="card-head"><div><p className="eyebrow">Zusammenarbeit</p><h2>Kommentare</h2></div></div>{canWrite&&!row.archived_at?<MentionPicker users={profiles} intent="comment" submitLabel="Kommentar speichern"/>:null}<div className="data-list">{comments.map((x:any)=><div className="data-row" key={x.id}><div><strong>{profileMap[x.author_user_id]??"Benutzer"}</strong><small>{formatDate(x.created_at)}</small><p>{x.body}</p></div></div>)}{comments.length===0?<p className="empty-state">Noch keine Kommentare.</p>:null}</div></section></div>
 <section className="data-card"><div className="card-head"><div><p className="eyebrow">Aktivität & Historie</p><h2>Nachvollziehbarkeit</h2></div></div><div className="history-list">{activity.slice(0,20).map((a:any)=><article className="history-event" key={`a-${a.id}`}><div className="history-head"><strong>{a.title??a.activity_type}</strong><small>{formatDate(a.occurred_at)}</small></div>{a.description?<p>{a.description}</p>:null}</article>)}{audit.slice(0,30).map((a:any)=><article className="history-event" key={`h-${a.id}`}><div className="history-head"><strong>{a.actor_display_name_snapshot??"System"} · {a.action}</strong><small>{formatDate(a.occurred_at)}</small></div>{a.description?<p>{a.description}</p>:null}</article>)}</div></section>
 </div><ConcurrencyConflictModal open={conflict} message="Bitte lade den aktuellen Stand neu. Deine Änderung wurde nicht überschrieben."/></main>;
}
