import { data, Form, Link, redirect, useActionData, useLoaderData } from "react-router";
import type { Route } from "./+types/lead-detail";
import { LeadTaskList } from "~/components/lead-task-list";
import { MentionPicker } from "~/components/mention-picker";
import { requirePermission } from "~/lib/auth.server";
import "~/lead.css";

type ActionResult={error?:string};
const STATUS:Record<string,string>={NEW:"Neu",CONTACTED:"Kontaktiert",QUALIFIED:"Qualifiziert",APPOINTMENT:"Termin",VALUATION:"Bewertung",OFFER:"Angebot",WON:"Gewonnen",NURTURE:"Nurture",LOST:"Verloren"};
const TYPES=[["DETACHED_HOUSE","Einfamilienhaus"],["SEMI_DETACHED_HOUSE","Doppelhaushälfte"],["TERRACED_HOUSE","Reihenhaus"],["APARTMENT_BUILDING","Mehrfamilienhaus"],["APARTMENT","Wohnung"],["PENTHOUSE","Penthouse"],["MAISONETTE","Maisonette"],["LAND","Grundstück"],["COMMERCIAL","Gewerbe"],["OFFICE","Büro"],["RETAIL","Einzelhandel"],["GARAGE","Garage"],["PARKING_SPACE","Stellplatz"],["OTHER","Sonstige"]] as const;
const FIELD:Record<string,string>={status:"Status",source_id:"Quelle",source_detail:"Quellendetail",lost_reason:"Verlustgrund",follow_up_at:"Wiedervorlage",primary_responsible_user:"Verantwortlich",property_street:"Straße",property_house_number:"Hausnummer",property_postal_code:"PLZ",property_city:"Ort",property_district:"Ortsteil",property_type:"Immobilientyp",year_built:"Baujahr",living_area_sqm:"Wohnfläche",plot_area_sqm:"Grundstück",rooms:"Zimmer",property_condition:"Zustand",occupancy_status:"Belegung",desired_sale_horizon:"Verkaufshorizont",price_expectation:"Preisvorstellung",message:"Hintergrund",internal_notes:"Interne Notizen",consent_given:"Einwilligung",valuation_appointment_at:"Bewertungstermin",estimated_market_value:"Marktwert",valuation_notes:"Bewertungsnotiz",offer_created_at:"Angebot erstellt",offered_commission_percent:"Provision %",offered_terms:"Konditionen",converted_property_id:"Immobilie"};
function text(fd:FormData,k:string){return String(fd.get(k)??"").trim();}
function numberValue(v:string){if(!v)return null;const normalized=v.includes(",")?v.replace(/\./g,"").replace(",","."):v;const n=Number(normalized);return Number.isFinite(n)?n:NaN;}
function one(v:any){return Array.isArray(v)?v[0]:v;}
function fmt(v:string|null){return v?new Intl.DateTimeFormat("de-DE",{dateStyle:"medium",timeStyle:"short",timeZone:"Europe/Berlin"}).format(new Date(v)):"—";}
function local(v:string|null){if(!v)return"";const p=new Intl.DateTimeFormat("en-CA",{timeZone:"Europe/Berlin",year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hourCycle:"h23"}).formatToParts(new Date(v));const g=(t:string)=>p.find(x=>x.type===t)?.value??"";return `${g("year")}-${g("month")}-${g("day")}T${g("hour")}:${g("minute")}`;}
function toIso(v:string){if(!v)return null;const m=v.match(/^(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2})$/);if(!m)return null;const target=Date.UTC(+m[1],+m[2]-1,+m[3],+m[4],+m[5]);let guess=target;for(let i=0;i<2;i++){const p=new Intl.DateTimeFormat("en-CA",{timeZone:"Europe/Berlin",year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hourCycle:"h23"}).formatToParts(new Date(guess));const g=(t:string)=>Number(p.find(x=>x.type===t)?.value);const shown=Date.UTC(g("year"),g("month")-1,g("day"),g("hour"),g("minute"));guess=target-(shown-guess);}return new Date(guess).toISOString();}
function acquisitionError(error:any){
  const message=String(error?.message??"");
  if(message.includes("ACQUISITION_WAVE_MISMATCH"))return"Die gewählte Welle gehört nicht zu dieser Kampagne.";
  if(message.includes("ACQUISITION_CAMPAIGN_NOT_FOUND"))return"Die gewählte Kampagne wurde nicht gefunden.";
  if(message.includes("ACQUISITION_REFERRER_ORGANIZATION_NOT_FOUND"))return"Der gewählte Partner wurde nicht gefunden.";
  if(message.includes("ACQUISITION_RESPONSE_IN_FUTURE"))return"Das Datum der Reaktion darf nicht in der Zukunft liegen.";
  if(message.includes("lead_acquisitions_wave_needs_campaign_check"))return"Eine Welle lässt sich nur zusammen mit ihrer Kampagne zuordnen.";
  return "Die Herkunft konnte nicht gespeichert werden.";
}
const RESPONSE_CHANNEL:Record<string,string>={QR_CODE:"QR-Code",PHONE:"Telefon",EMAIL:"E-Mail",WEB_FORM:"Formular",LETTER:"Brief",IN_PERSON:"Persönlich",EVENT:"Veranstaltung",OTHER:"Sonstiges"};
function show(v:any){if(v===null||v===undefined||v==="")return"—";if(typeof v==="boolean")return v?"Ja":"Nein";return typeof v==="object"?JSON.stringify(v):String(v);}

export async function loader({request,context,params}:Route.LoaderArgs){
  const {supabase,responseHeaders,profile}=await requirePermission(request,context.cloudflare.env,"lead.read"); const leadId=params.leadId; if(!leadId)throw new Response("Lead fehlt.",{status:404});
  const {data:lead,error}=await supabase.from("leads").select("*,contacts!inner(id,contact_number,first_name,last_name,email,phone,mobile,preferred_channel),lead_sources(id,key,label)").eq("id",leadId).maybeSingle(); if(error||!lead)throw new Response("Lead nicht gefunden.",{status:404});
  const [transitionResult,sourceResult,profileResult,activityResult,commentResult,taskResult,auditResult,acquisitionResult,campaignResult,waveResult,organizationResult]=await Promise.all([
    supabase.from("lead_status_transitions").select("to_status,description").eq("from_status",lead.status),
    supabase.from("lead_sources").select("id,key,label,sort_order").eq("active",true).order("sort_order"),
    supabase.from("profiles").select("user_id,display_name,status").eq("status","ACTIVE").order("display_name"),
    supabase.from("activity_events").select("id,activity_type,title,description,actor_user_id,occurred_at").eq("lead_id",leadId).order("occurred_at",{ascending:false}).limit(100),
    supabase.from("comments").select("id,body,author_user_id,created_at").eq("entity_type","LEAD").eq("entity_id",leadId).is("archived_at",null).order("created_at",{ascending:false}).limit(100),
    supabase.from("tasks").select("id,task_number,title,description,status,priority,due_at,responsible_user").eq("lead_id",leadId).is("archived_at",null).order("due_at",{ascending:true}).limit(100),
    supabase.from("audit_events").select("id,actor_display_name_snapshot,action,field_changes,occurred_at").eq("entity_type","LEAD").eq("entity_id",leadId).order("occurred_at",{ascending:false}).limit(100),
    supabase.from("lead_acquisitions").select("*").eq("lead_id",leadId).maybeSingle(),
    supabase.from("acquisition_campaigns").select("id,campaign_number,name,acquisition_areas(name)").is("archived_at",null).order("created_at",{ascending:false}).limit(200),
    supabase.from("acquisition_waves").select("id,campaign_id,wave_position,name").order("wave_position").limit(500),
    supabase.from("organizations").select("id,organization_number,name").is("archived_at",null).order("name").limit(500),
  ]);
  if(transitionResult.error||sourceResult.error||profileResult.error||activityResult.error||commentResult.error||taskResult.error||auditResult.error)throw new Response("Lead-Arbeitsbereich konnte nicht geladen werden.",{status:500});
  const mandateResult=await supabase.from("brokerage_mandates").select("id,mandate_number,mandate_type,status,term_start").eq("lead_id",lead.id).is("archived_at",null).order("updated_at",{ascending:false}).limit(10);
  const permissionRows=await Promise.all(["lead.write","lead.assign","lead.archive","lead.convert","property.write","property.assign","task.write"].map(async key=>({key,allowed:(await supabase.rpc("current_user_has_permission",{p_permission:key})).data===true})));
  const permissions:Record<string,boolean>=Object.fromEntries(permissionRows.map(p=>[p.key,p.allowed])); const profiles=profileResult.data??[]; const comments=commentResult.data??[]; const profileMap=Object.fromEntries(profiles.map((p:any)=>[p.user_id,p.display_name]));
  let mentionRows:any[]=[]; const commentIds=comments.map((c:any)=>c.id); if(commentIds.length){const {data:mentions}=await supabase.from("comment_mentions").select("comment_id,mentioned_user_id").in("comment_id",commentIds);mentionRows=mentions??[];} const mentionsByComment=mentionRows.reduce((a:any,m:any)=>{(a[m.comment_id]??=[]).push(m.mentioned_user_id);return a;},{});
  return data({lead,acquisition:acquisitionResult.data??null,campaigns:campaignResult.data??[],waves:waveResult.data??[],organizations:organizationResult.data??[],mandates:mandateResult.error?[]:(mandateResult.data??[]),transitions:transitionResult.data??[],sources:sourceResult.data??[],profiles,profileMap,activities:activityResult.data??[],comments,mentionsByComment,tasks:taskResult.data??[],audit:auditResult.data??[],permissions,profile},{headers:responseHeaders()});
}

export async function action({request,context,params}:Route.ActionArgs){
  const fd=await request.formData(); const intent=text(fd,"_intent"); const {supabase,responseHeaders,userId}=await requirePermission(request,context.cloudflare.env,intent==="create_task"?"task.write":"lead.write"); const leadId=params.leadId;if(!leadId)throw new Response("Lead fehlt.",{status:404}); const version=Number(text(fd,"version"));
  const extra=async(permission:string)=>(await supabase.rpc("current_user_has_permission",{p_permission:permission})).data===true;
  const save=async(update:Record<string,unknown>)=>{const {data:updated,error}=await supabase.from("leads").update(update).eq("id",leadId).eq("version",version).select("id").maybeSingle();if(error)return data<ActionResult>({error:"Lead konnte nicht gespeichert werden. Eingaben und Berechtigungen prüfen."},{status:400,headers:responseHeaders()});if(!updated)return data<ActionResult>({error:"Der Lead wurde zwischenzeitlich geändert. Bitte neu laden."},{status:409,headers:responseHeaders()});return redirect(`/leads/${leadId}`,{headers:responseHeaders()});};
  if(intent==="core"){const nums={year_built:numberValue(text(fd,"year_built")),living_area_sqm:numberValue(text(fd,"living_area_sqm")),plot_area_sqm:numberValue(text(fd,"plot_area_sqm")),rooms:numberValue(text(fd,"rooms")),price_expectation:numberValue(text(fd,"price_expectation")),estimated_market_value:numberValue(text(fd,"estimated_market_value")),offered_commission_percent:numberValue(text(fd,"offered_commission_percent"))};if(Object.values(nums).some(v=>typeof v==="number"&&!Number.isFinite(v)))return data<ActionResult>({error:"Ungültiger Zahlenwert."},{status:400,headers:responseHeaders()});const consent=fd.get("consent_given")==="on";return save({source_id:text(fd,"source_id")||null,source_detail:text(fd,"source_detail")||null,follow_up_at:toIso(text(fd,"follow_up_at")),property_street:text(fd,"property_street")||null,property_house_number:text(fd,"property_house_number")||null,property_postal_code:text(fd,"property_postal_code")||null,property_city:text(fd,"property_city")||null,property_district:text(fd,"property_district")||null,property_type:text(fd,"property_type")||null,year_built:nums.year_built,living_area_sqm:nums.living_area_sqm,plot_area_sqm:nums.plot_area_sqm,rooms:nums.rooms,property_condition:text(fd,"property_condition")||null,occupancy_status:text(fd,"occupancy_status")||null,desired_sale_horizon:text(fd,"desired_sale_horizon")||null,price_expectation:nums.price_expectation,message:text(fd,"message")||null,internal_notes:text(fd,"internal_notes")||null,consent_given:consent,consent_at:consent?(text(fd,"consent_at")||new Date().toISOString()):null,consent_text_version:consent?(text(fd,"consent_text_version")||"CRM-2026-08"):null,valuation_appointment_at:toIso(text(fd,"valuation_appointment_at")),estimated_market_value:nums.estimated_market_value,valuation_notes:text(fd,"valuation_notes")||null,offer_created_at:toIso(text(fd,"offer_created_at")),offered_commission_percent:nums.offered_commission_percent,offered_terms:text(fd,"offered_terms")||null});}
  if(intent==="status"){const target=text(fd,"target_status"),lost=text(fd,"lost_reason");if(target==="LOST"&&!lost)return data<ActionResult>({error:"Für Verloren ist ein Verlustgrund erforderlich."},{status:400,headers:responseHeaders()});return save({status:target,lost_reason:target==="LOST"?lost:null});}
  if(intent==="assign"){if(!(await extra("lead.assign")))return data<ActionResult>({error:"Keine Berechtigung zur Lead-Zuweisung."},{status:403,headers:responseHeaders()});return save({primary_responsible_user:text(fd,"primary_responsible_user")});}
  if(intent==="archive"||intent==="restore"){if(!(await extra("lead.archive")))return data<ActionResult>({error:"Keine Archiv-Berechtigung."},{status:403,headers:responseHeaders()});return save({archived_at:intent==="archive"?new Date().toISOString():null});}
  if(intent==="acquisition_save"){
    const campaignId=text(fd,"campaign_id")||null;
    const waveId=text(fd,"wave_id")||null;
    // Eine Welle ohne Kampagne wäre eine Zuordnung ins Leere; die Datenbank
    // weist das ab, der Hinweis gehört aber ans Formular.
    if(waveId&&!campaignId)return data<ActionResult>({error:"Eine Welle lässt sich nur zusammen mit ihrer Kampagne zuordnen."},{status:400,headers:responseHeaders()});
    const responseOn=text(fd,"response_on");
    if(responseOn&&!/^\d{4}-\d{2}-\d{2}$/.test(responseOn))return data<ActionResult>({error:"Ungültiges Datum der Reaktion."},{status:400,headers:responseHeaders()});
    const payload={campaign_id:campaignId,wave_id:waveId,referrer_organization_id:text(fd,"referrer_organization_id")||null,response_channel:text(fd,"response_channel")||null,response_on:responseOn||null,notes:text(fd,"acquisition_notes")||null};
    const existingId=text(fd,"acquisition_id");
    if(existingId){
      const {data:updated,error}=await supabase.from("lead_acquisitions").update(payload).eq("id",existingId).eq("version",Number(text(fd,"acquisition_version"))).select("id").maybeSingle();
      if(error)return data<ActionResult>({error:acquisitionError(error)},{status:400,headers:responseHeaders()});
      if(!updated)return data<ActionResult>({error:"Die Herkunft wurde zwischenzeitlich geändert. Bitte Seite neu laden."},{status:409,headers:responseHeaders()});
    }else{
      const {error}=await supabase.from("lead_acquisitions").insert({...payload,lead_id:leadId,created_by:userId,updated_by:userId});
      if(error)return data<ActionResult>({error:acquisitionError(error)},{status:400,headers:responseHeaders()});
    }
    return redirect(`/leads/${leadId}#herkunft`,{headers:responseHeaders()});
  }
  if(intent==="add_activity"){const title=text(fd,"title");if(!title)return data<ActionResult>({error:"Aktivität benötigt einen Titel."},{status:400,headers:responseHeaders()});const {error}=await supabase.from("activity_events").insert({activity_type:text(fd,"activity_type")||"NOTE",title,description:text(fd,"description")||null,actor_user_id:userId,lead_id:leadId});if(error)return data<ActionResult>({error:"Aktivität konnte nicht gespeichert werden."},{status:400,headers:responseHeaders()});return redirect(`/leads/${leadId}`,{headers:responseHeaders()});}
  if(intent==="add_comment"){const body=text(fd,"body");if(!body)return data<ActionResult>({error:"Kommentar darf nicht leer sein."},{status:400,headers:responseHeaders()});const {error}=await supabase.rpc("create_lead_comment",{p_lead_id:leadId,p_body:body,p_mentioned_user_ids:fd.getAll("mention_user_id").map(String).filter(Boolean)});if(error)return data<ActionResult>({error:"Kommentar/Mention konnte nicht gespeichert werden."},{status:400,headers:responseHeaders()});return redirect(`/leads/${leadId}`,{headers:responseHeaders()});}
  if(intent==="create_task"){const title=text(fd,"title"),due=toIso(text(fd,"due_at"));if(!title||!due)return data<ActionResult>({error:"Aufgabe benötigt Titel und Fälligkeit."},{status:400,headers:responseHeaders()});const {data:lead}=await supabase.from("leads").select("contact_id").eq("id",leadId).single();const {error}=await supabase.from("tasks").insert({title,description:text(fd,"description")||null,status:"OPEN",priority:text(fd,"priority")||"NORMAL",due_at:due,responsible_user:text(fd,"responsible_user")||userId,contact_id:lead?.contact_id??null,lead_id:leadId,created_by:userId,updated_by:userId});if(error)return data<ActionResult>({error:"Aufgabe konnte nicht angelegt werden."},{status:400,headers:responseHeaders()});return redirect(`/leads/${leadId}`,{headers:responseHeaders()});}
  if(intent==="convert"){
    if(!(await extra("lead.convert")))return data<ActionResult>({error:"Keine Konvertierungs-Berechtigung."},{status:403,headers:responseHeaders()});
    const {data:current}=await supabase.from("leads").select("status,property_type,property_street,property_house_number,property_postal_code,property_city").eq("id",leadId).maybeSingle();
    if(!current)return data<ActionResult>({error:"Lead nicht gefunden."},{status:404,headers:responseHeaders()});
    if(current.status!=="WON")return data<ActionResult>({error:"Der Lead muss zuerst den Status „Gewonnen“ haben."},{status:400,headers:responseHeaders()});
    if(!current.property_type)return data<ActionResult>({error:"Vor der Übernahme bitte einen Immobilientyp auswählen und den Lead speichern."},{status:400,headers:responseHeaders()});
    const addressParts=[current.property_street,current.property_house_number,current.property_postal_code,current.property_city];
    if(addressParts.some(Boolean)&&!addressParts.every(Boolean))return data<ActionResult>({error:"Die Objektadresse ist teilweise gefüllt. Bitte Straße, Hausnummer, PLZ und Ort vollständig speichern oder die Adresse leeren."},{status:400,headers:responseHeaders()});
    const {data:propertyId,error}=await supabase.rpc("convert_lead_to_property",{p_lead_id:leadId,p_expected_version:version,p_internal_title:text(fd,"internal_title")||null});
    if(error||!propertyId)return data<ActionResult>({error:"Immobilie konnte nicht erzeugt werden. Bitte Lead neu laden und die Pflichtangaben prüfen."},{status:400,headers:responseHeaders()});
    return redirect(`/properties/${propertyId}?fromLead=${encodeURIComponent(leadId)}&setup=1`,{headers:responseHeaders()});
  }
  return data<ActionResult>({error:"Unbekannte Aktion."},{status:400,headers:responseHeaders()});
}

function CoreForm({lead,sources,permissions}:{lead:any;sources:any[];permissions:Record<string,boolean>}){
  return <Form method="post" className="auth-form"><input type="hidden" name="_intent" value="core"/><input type="hidden" name="version" value={lead.version}/><input type="hidden" name="consent_at" value={lead.consent_at??""}/><div className="form-grid">
    <label><span>Quelle</span><select name="source_id" defaultValue={lead.source_id??""}><option value="">Quelle offen</option>{sources.map((s:any)=><option key={s.id} value={s.id}>{s.label}</option>)}</select></label><label><span>Quellendetail</span><input name="source_detail" defaultValue={lead.source_detail??""}/></label>
    <label><span>Wiedervorlage</span><input name="follow_up_at" type="datetime-local" defaultValue={local(lead.follow_up_at)}/></label><label><span>Immobilientyp</span><select name="property_type" defaultValue={lead.property_type??""}><option value="">Noch offen</option>{TYPES.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>
    <label><span>Straße</span><input name="property_street" defaultValue={lead.property_street??""}/></label><label><span>Hausnummer</span><input name="property_house_number" defaultValue={lead.property_house_number??""}/></label><label><span>PLZ</span><input name="property_postal_code" defaultValue={lead.property_postal_code??""}/></label><label><span>Ort</span><input name="property_city" defaultValue={lead.property_city??""}/></label><label><span>Ortsteil</span><input name="property_district" defaultValue={lead.property_district??""}/></label>
    <label><span>Baujahr</span><input name="year_built" defaultValue={lead.year_built??""}/></label><label><span>Wohnfläche m²</span><input name="living_area_sqm" defaultValue={lead.living_area_sqm??""}/></label><label><span>Grundstück m²</span><input name="plot_area_sqm" defaultValue={lead.plot_area_sqm??""}/></label><label><span>Zimmer</span><input name="rooms" defaultValue={lead.rooms??""}/></label><label><span>Zustand</span><input name="property_condition" defaultValue={lead.property_condition??""}/></label>
    <label><span>Belegung</span><select name="occupancy_status" defaultValue={lead.occupancy_status??"UNKNOWN"}><option value="UNKNOWN">Unbekannt</option><option value="VACANT">Leer</option><option value="OWNER_OCCUPIED">Eigengenutzt</option><option value="RENTED">Vermietet</option><option value="PARTIALLY_RENTED">Teilvermietet</option></select></label><label><span>Verkaufshorizont</span><input name="desired_sale_horizon" defaultValue={lead.desired_sale_horizon??""}/></label><label><span>Preisvorstellung €</span><input name="price_expectation" defaultValue={lead.price_expectation??""}/></label>
    <label><span>Bewertungstermin</span><input name="valuation_appointment_at" type="datetime-local" defaultValue={local(lead.valuation_appointment_at)}/></label><label><span>Geschätzter Marktwert €</span><input name="estimated_market_value" defaultValue={lead.estimated_market_value??""}/></label><label><span>Angebot erstellt</span><input name="offer_created_at" type="datetime-local" defaultValue={local(lead.offer_created_at)}/></label><label><span>Provision %</span><input name="offered_commission_percent" defaultValue={lead.offered_commission_percent??""}/></label>
  </div><label><span>Nachricht / Hintergrund</span><textarea name="message" rows={3} defaultValue={lead.message??""}/></label><label><span>Bewertungsnotiz</span><textarea name="valuation_notes" rows={3} defaultValue={lead.valuation_notes??""}/></label><label><span>Angebotskonditionen</span><textarea name="offered_terms" rows={3} defaultValue={lead.offered_terms??""}/></label><label><span>Interne Notizen</span><textarea name="internal_notes" rows={3} defaultValue={lead.internal_notes??""}/></label><label className="checkbox-row"><input type="checkbox" name="consent_given" defaultChecked={lead.consent_given}/><span>Einwilligung dokumentiert</span></label><label><span>Consent-Textversion</span><input name="consent_text_version" defaultValue={lead.consent_text_version??"CRM-2026-08"}/></label>{permissions["lead.write"]&&!lead.archived_at?<button className="primary-button" type="submit">Lead speichern</button>:null}</Form>;
}

export default function LeadDetail(){
  const {lead,acquisition,campaigns,waves,organizations,mandates,transitions,sources,profiles,profileMap,activities,comments,mentionsByComment,tasks,audit,permissions,profile}=useLoaderData<typeof loader>(); const result=useActionData<typeof action>(); const contact=one(lead.contacts),source=one(lead.lead_sources); const mentionable=profiles.filter((p:any)=>p.user_id!==profile.user_id); const overdue=lead.follow_up_at&&new Date(lead.follow_up_at).getTime()<Date.now();
  const permissionReady=permissions["lead.convert"]&&permissions["property.write"]&&(lead.primary_responsible_user===profile.user_id||permissions["property.assign"]); const addressParts=[lead.property_street,lead.property_house_number,lead.property_postal_code,lead.property_city]; const partialAddress=addressParts.some(Boolean)&&!addressParts.every(Boolean); const conversionMissing:string[]=[]; if(!lead.property_type)conversionMissing.push("Immobilientyp auswählen und speichern"); if(partialAddress)conversionMissing.push("Objektadresse vollständig speichern"); if(!permissionReady)conversionMissing.push("Berechtigung für Lead-/Immobilienübernahme"); const conversionReady=conversionMissing.length===0;
  return <main className="editor-shell lead-shell">
    <header className="editor-header"><div><Link className="back-link" to="/leads">← Verkäufer-Leads</Link><p className="eyebrow">{lead.lead_number} · {source?.label??"Quelle offen"}</p><div className="lead-inline-meta"><h1 className="editor-title">{contact.first_name} {contact.last_name}</h1><span className="lead-status-pill">{STATUS[lead.status]??lead.status}</span>{lead.archived_at?<span className="badge">ARCHIVIERT</span>:null}</div><p className="editor-meta">Potenzieller Verkaufs-/Bewertungsauftrag · Version {lead.version} · geändert {fmt(lead.updated_at)}</p></div><div className="header-user"><span className="badge">{__APP_ENV_LABEL__}</span><small>{profile.display_name}</small></div></header>
    <div className="lead-detail-width">
      {result?.error?<div className="form-error">{result.error}</div>:null}
      <div className="lead-summary-grid"><div className="lead-summary-card"><small>Kontakt</small><strong>{contact.contact_number}</strong></div><div className="lead-summary-card"><small>Verantwortlich</small><strong>{profileMap[lead.primary_responsible_user]??"—"}</strong></div><div className="lead-summary-card"><small>Wiedervorlage</small><strong className={overdue?"lead-overdue":""}>{fmt(lead.follow_up_at)}</strong></div><div className="lead-summary-card"><small>Erstellt</small><strong>{fmt(lead.created_at)}</strong></div></div>
      <section className="data-card lead-readiness-entry"><div><p className="eyebrow">Neue Verkaufsstrategie</p><h2>Verkaufsstrategie-Check</h2><p>Ausgangslage dokumentieren, drei Verkaufsszenarien vergleichen und sinnvolle Maßnahmen priorisieren.</p></div><div><span className="lead-readiness-state">Backend vorbereitet · noch nicht aktiviert</span><Link className="primary-button link-button" to={`/leads/${lead.id}/sales-readiness`}>Arbeitsbereich öffnen →</Link></div></section>
      <div className="lead-detail-grid"><div className="lead-section-stack">
        <section className="data-card"><div className="card-head"><div><p className="eyebrow">Pipeline</p><h2>{STATUS[lead.status]}</h2><p className="lead-card-caption">Hier steuerst du den Weg vom Erstkontakt bis zum gewonnenen Maklerauftrag.</p></div></div>{!lead.archived_at?<div className="lead-transition-grid">{transitions.filter((t:any)=>t.to_status!=="LOST").map((t:any)=><Form method="post" key={t.to_status}><input type="hidden" name="_intent" value="status"/><input type="hidden" name="version" value={lead.version}/><input type="hidden" name="target_status" value={t.to_status}/><button className="secondary-button" type="submit" title={t.description??""}>→ {STATUS[t.to_status]}</button></Form>)}</div>:null}{!lead.archived_at&&transitions.some((t:any)=>t.to_status==="LOST")?<Form method="post" className="lead-lost-form"><input type="hidden" name="_intent" value="status"/><input type="hidden" name="version" value={lead.version}/><input type="hidden" name="target_status" value="LOST"/><input name="lost_reason" required placeholder="Warum wurde der Lead verloren?"/><button className="secondary-button" type="submit">Verloren</button></Form>:null}{lead.lost_reason?<p className="form-help">Verlustgrund: {lead.lost_reason}</p>:null}</section>
        <section className="data-card"><div className="card-head"><div><p className="eyebrow">Objekt & Bewertung</p><h2>Angaben zum möglichen Auftrag</h2><p className="lead-card-caption">Die hier erfassten Angaben werden bei der späteren Übernahme in die Immobilie übernommen.</p></div></div><CoreForm lead={lead} sources={sources} permissions={permissions}/></section>
        <section className="data-card" id="herkunft"><div className="card-head"><div><p className="eyebrow">Kanal › Kampagne › Welle</p><h2>Herkunft</h2><p className="lead-card-caption">Woraus dieser Lead entstanden ist. Grundlage der Kampagnen- und Partnerauswertung.</p></div><Link className="subtle-link" to="/acquisition">Kampagnen →</Link></div>
        <Form method="post" className="form-grid">
          <input type="hidden" name="_intent" value="acquisition_save"/>
          <input type="hidden" name="acquisition_id" value={(acquisition as any)?.id??""}/>
          <input type="hidden" name="acquisition_version" value={(acquisition as any)?.version??0}/>
          <label className="form-field"><span>Kampagne</span><select name="campaign_id" defaultValue={(acquisition as any)?.campaign_id??""} disabled={!permissions["lead.write"]}><option value="">—</option>{(campaigns as any[]).map((c:any)=><option key={c.id} value={c.id}>{c.campaign_number} · {c.name}{c.acquisition_areas?.name?` (${c.acquisition_areas.name})`:""}</option>)}</select></label>
          <label className="form-field"><span>Welle</span><select name="wave_id" defaultValue={(acquisition as any)?.wave_id??""} disabled={!permissions["lead.write"]}><option value="">—</option>{(waves as any[]).map((w:any)=><option key={w.id} value={w.id}>{((campaigns as any[]).find((c:any)=>c.id===w.campaign_id)?.campaign_number)??"?"} · {w.wave_position}. {w.name}</option>)}</select><small className="subtle">Nur zusammen mit der passenden Kampagne.</small></label>
          <label className="form-field"><span>Empfehlender Partner</span><select name="referrer_organization_id" defaultValue={(acquisition as any)?.referrer_organization_id??""} disabled={!permissions["lead.write"]}><option value="">—</option>{(organizations as any[]).map((o:any)=><option key={o.id} value={o.id}>{o.name}</option>)}</select><small className="subtle">Zeigt auf den konkreten Partner, nicht auf eine Quellenkategorie.</small></label>
          <label className="form-field"><span>Reaktionsweg</span><select name="response_channel" defaultValue={(acquisition as any)?.response_channel??""} disabled={!permissions["lead.write"]}><option value="">—</option>{Object.entries(RESPONSE_CHANNEL).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label>
          <label className="form-field"><span>Reaktion am</span><input type="date" name="response_on" defaultValue={(acquisition as any)?.response_on??""} disabled={!permissions["lead.write"]}/></label>
          <label className="form-field full-width"><span>Notiz</span><input name="acquisition_notes" defaultValue={(acquisition as any)?.notes??""} disabled={!permissions["lead.write"]}/></label>
          <div className="form-field full-width inline-actions"><button className="secondary-button" type="submit" disabled={!permissions["lead.write"]}>Herkunft speichern</button></div>
        </Form>
        {!acquisition?<p className="form-help">Ohne Zuordnung erscheint dieser Lead in keiner Kampagnen- oder Partnerauswertung.</p>:null}</section>
        <section className="data-card"><div className="card-head"><div><p className="eyebrow">Vorbereitung</p><h2>Unterlagen & Medien</h2></div></div><div className="lead-prep-grid"><div className="lead-prep-item"><strong>Dokumente zusammentragen</strong><small>z. B. Grundbuchauszug, Energieausweis, Grundriss, Teilungserklärung oder weitere Objektunterlagen.</small></div><div className="lead-prep-item"><strong>Fotos & Grundrisse planen</strong><small>Bildmaterial kann vorbereitet werden; der eigentliche Upload erfolgt nach der Objektübernahme in der privaten Immobilienakte.</small></div></div><p className="form-help">So bleiben Dateien sauber an die spätere Immobilie gebunden. Nach der Übernahme bekommst du direkte Links zu Dokumenten und Medien.</p></section>
        <section className="data-card"><div className="card-head"><div><p className="eyebrow">Beauftragung</p><h2>Maklerauftrag</h2><p className="lead-card-caption">Auftragsart, Laufzeit, Provisionsvereinbarung und Widerrufsdokumentation.</p></div><Link className="subtle-link" to={lead.converted_property_id?`/mandates/new?property_id=${encodeURIComponent(lead.converted_property_id)}`:"/mandates"}>Auftrag anlegen →</Link></div><div className="history-list">{mandates.map((m:any)=><Link className="data-row data-row-link" to={`/mandates/${m.id}`} key={m.id}><div><strong>{m.mandate_number}</strong><small>{m.mandate_type} · {m.status}</small></div><span className="subtle-link">Öffnen →</span></Link>)}{mandates.length===0?<p className="empty-state">Zu diesem Lead ist kein Maklerauftrag verknüpft.</p>:null}</div></section>
        <section className="data-card lead-conversion-card"><div className="card-head"><div><p className="eyebrow">Lead → Immobilie</p><h2>Auftrag übernehmen</h2></div></div>{lead.converted_property_id?<div className="lead-conversion-success"><strong>Bereits als Immobilie angelegt.</strong><p>Der Lead bleibt als Herkunft verknüpft.</p><Link className="primary-button link-button" to={`/properties/${lead.converted_property_id}?fromLead=${lead.id}&setup=1`}>Immobilie öffnen →</Link></div>:lead.status!=="WON"?<p className="empty-state">Sobald der Auftrag gewonnen ist, kann daraus hier die Immobilie angelegt werden.</p>:<Form method="post" className="auth-form"><p>Kontakt wird als 100%-Eigentümer übernommen; gespeicherte Adresse, Objektwerte und Verantwortlicher werden übertragen.</p><input type="hidden" name="_intent" value="convert"/><input type="hidden" name="version" value={lead.version}/><label><span>Interner Objekttitel <small>(optional)</small></span><input name="internal_title" placeholder={`z. B. ${contact.last_name} · ${lead.property_city??"Objekt"}`}/></label>{conversionMissing.length?<div className="lead-conversion-readiness"><strong>Vor der Übernahme noch erforderlich:</strong><ul>{conversionMissing.map(item=><li key={item}>{item}</li>)}</ul></div>:<div className="form-success">Bereit zur Übernahme. Danach wirst du direkt in die neue Immobilienakte weitergeleitet.</div>}<button className="primary-button" type="submit" disabled={!conversionReady}>In Immobilie übernehmen</button></Form>}</section>
        <section className="data-card"><div className="card-head"><div><p className="eyebrow">Audit</p><h2>Änderungshistorie</h2></div></div><div className="history-list">{audit.map((e:any)=><article className="history-event" key={e.id}><div className="history-head"><strong>{e.action}</strong><small>{fmt(e.occurred_at)} · {e.actor_display_name_snapshot??"System"}</small></div>{Object.entries(e.field_changes??{}).map(([k,v]:any)=><div className="lead-history-change" key={k}><strong>{FIELD[k]??k}</strong><code>{v&&typeof v==="object"&&("old" in v||"new" in v)?`${show(v.old)} → ${show(v.new)}`:show(v)}</code></div>)}</article>)}{audit.length===0?<p className="empty-state">Noch keine Audit-Ereignisse.</p>:null}</div></section>
      </div><aside className="lead-section-stack">
        <section className="data-card"><div className="card-head"><div><p className="eyebrow">Kontakt</p><h2>{contact.first_name} {contact.last_name}</h2></div></div><div className="lead-contact-box"><span>{contact.email??"—"}</span><span>{contact.mobile??contact.phone??"—"}</span><span>Bevorzugt: {contact.preferred_channel??"—"}</span><Link className="subtle-link" to={`/crm/contacts/${contact.id}`}>Kontaktakte →</Link></div></section>
        <section className="data-card"><div className="card-head"><div><p className="eyebrow">Zuständigkeit</p><h2>Verantwortlicher</h2></div></div><Form method="post" className="auth-form"><input type="hidden" name="_intent" value="assign"/><input type="hidden" name="version" value={lead.version}/><select name="primary_responsible_user" defaultValue={lead.primary_responsible_user}>{profiles.map((p:any)=><option key={p.user_id} value={p.user_id}>{p.display_name}</option>)}</select><button className="secondary-button" disabled={!permissions["lead.assign"]||Boolean(lead.archived_at)}>Zuordnen</button></Form></section>
        <section className="data-card"><div className="card-head"><div><p className="eyebrow">Wiedervorlage</p><h2>Aufgaben</h2><p className="lead-card-caption">Aufgabe anklicken, um Titel, Beschreibung und Details im Fenster zu öffnen.</p></div></div>{permissions["task.write"]?<Form method="post" className="auth-form"><input type="hidden" name="_intent" value="create_task"/><label><span>Titel *</span><input name="title" defaultValue={`Wiedervorlage ${lead.lead_number}`} required/></label><label><span>Beschreibung</span><textarea name="description" rows={3} placeholder="Was genau soll erledigt werden?"/></label><label><span>Fällig *</span><input name="due_at" type="datetime-local" defaultValue={local(lead.follow_up_at)} required/></label><label><span>Priorität</span><select name="priority" defaultValue="NORMAL"><option value="LOW">Niedrig</option><option value="NORMAL">Normal</option><option value="HIGH">Hoch</option><option value="URGENT">Dringend</option></select></label><label><span>Verantwortlich</span><select name="responsible_user" defaultValue={lead.primary_responsible_user}>{profiles.map((p:any)=><option key={p.user_id} value={p.user_id}>{p.display_name}</option>)}</select></label><button className="secondary-button">Aufgabe anlegen</button></Form>:null}<LeadTaskList tasks={tasks as any} profileMap={profileMap}/></section>
        <section className="data-card"><div className="card-head"><div><p className="eyebrow">Activity</p><h2>Aktivitäten</h2></div></div><Form method="post" className="auth-form"><input type="hidden" name="_intent" value="add_activity"/><select name="activity_type" defaultValue="NOTE"><option value="NOTE">Notiz</option><option value="PHONE_CALL">Telefonat</option><option value="EMAIL">E-Mail</option><option value="MEETING">Termin</option></select><input name="title" required placeholder="Titel"/><textarea name="description" rows={2} placeholder="Beschreibung"/><button className="secondary-button">Speichern</button></Form><div className="history-list">{activities.slice(0,10).map((a:any)=><article className="history-event" key={a.id}><div className="history-head"><strong>{a.title??a.activity_type}</strong><small>{fmt(a.occurred_at)}</small></div>{a.description?<div className="history-change"><small>{a.description}</small></div>:null}</article>)}{!activities.length?<p className="empty-state">Keine Aktivitäten.</p>:null}</div></section>
        <section className="data-card"><div className="card-head"><div><p className="eyebrow">Team</p><h2>Kommentare & @Mentions</h2></div></div><Form method="post" className="auth-form"><input type="hidden" name="_intent" value="add_comment"/><label><span>Kommentar</span><textarea name="body" rows={3} required placeholder="Interner Kommentar"/></label><MentionPicker users={mentionable as any}/><button className="secondary-button">Kommentar speichern</button></Form><div className="history-list">{comments.map((c:any)=><article className="history-event" key={c.id}><div className="history-head"><strong>{profileMap[c.author_user_id]??"Benutzer"}</strong><small>{fmt(c.created_at)}</small></div><div className="history-change"><small>{c.body}</small></div>{(mentionsByComment[c.id]??[]).length?<p>{(mentionsByComment[c.id]??[]).map((id:string)=>`@${profileMap[id]??"Benutzer"}`).join(" · ")}</p>:null}</article>)}{!comments.length?<p className="empty-state">Keine Kommentare.</p>:null}</div></section>
        <section className="data-card"><div className="card-head"><div><p className="eyebrow">Datensatz</p><h2>Archiv</h2></div></div><Form method="post"><input type="hidden" name="_intent" value={lead.archived_at?"restore":"archive"}/><input type="hidden" name="version" value={lead.version}/><button className={lead.archived_at?"secondary-button":"text-button"} disabled={!permissions["lead.archive"]}>{lead.archived_at?"Lead wiederherstellen":"Lead archivieren"}</button></Form></section>
      </aside></div>
    </div>
  </main>;
}
