import { data, Form, Link, useLoaderData } from "react-router";
import type { Route } from "./+types/leads";
import { requirePermission } from "~/lib/auth.server";
import "~/lead.css";

const STATUS_ORDER=["NEW","CONTACTED","QUALIFIED","APPOINTMENT","VALUATION","OFFER","WON","NURTURE","LOST"] as const;
const STATUS_LABELS:Record<string,string>={NEW:"Neu",CONTACTED:"Kontaktiert",QUALIFIED:"Qualifiziert",APPOINTMENT:"Termin",VALUATION:"Bewertung",OFFER:"Angebot",WON:"Gewonnen",NURTURE:"Nurture",LOST:"Verloren"};
function one(value:any){return Array.isArray(value)?value[0]:value;}
function fmt(value:string|null){return value?new Intl.DateTimeFormat("de-DE",{dateStyle:"short",timeStyle:"short",timeZone:"Europe/Berlin"}).format(new Date(value)):"—";}
function address(row:any){return [row.property_street,row.property_house_number].filter(Boolean).join(" ")+(row.property_postal_code||row.property_city?`, ${[row.property_postal_code,row.property_city].filter(Boolean).join(" ")}`:"");}

export async function loader({request,context}:Route.LoaderArgs){
  const {supabase,responseHeaders,profile}=await requirePermission(request,context.cloudflare.env,"lead.read");
  const url=new URL(request.url); const q=(url.searchParams.get("q")??"").trim().toLowerCase(); const status=url.searchParams.get("status")??"ALL"; const source=url.searchParams.get("source")??"ALL"; const responsible=url.searchParams.get("responsible")??"ALL"; const followup=url.searchParams.get("followup")??"ALL"; const archived=url.searchParams.get("archived")==="1"; const page=Math.max(1,Number(url.searchParams.get("page")??"1")||1); const pageSize=50;
  const [{data:rows,error},{data:sources},{data:profiles}]=await Promise.all([
    supabase.from("leads").select("id,lead_number,status,source_id,follow_up_at,primary_responsible_user,property_street,property_house_number,property_postal_code,property_city,created_at,updated_at,archived_at,contacts!inner(id,first_name,last_name,email,phone,mobile),lead_sources(id,key,label)").order("updated_at",{ascending:false}).limit(500),
    supabase.from("lead_sources").select("id,key,label,sort_order").eq("active",true).order("sort_order"),
    supabase.from("profiles").select("user_id,display_name,status").eq("status","ACTIVE").order("display_name")
  ]);
  if(error)throw new Response("Leads konnten nicht geladen werden.",{status:500});
  const now=Date.now(); const activeRows=(rows??[]).filter((r:any)=>archived?Boolean(r.archived_at):!r.archived_at);
  const pipeline=STATUS_ORDER.map(s=>({status:s,count:activeRows.filter((r:any)=>r.status===s).length,overdue:activeRows.filter((r:any)=>r.status===s&&r.follow_up_at&&new Date(r.follow_up_at).getTime()<now).length}));
  let filtered=activeRows.filter((r:any)=>{
    const c=one(r.contacts); const hay=[r.lead_number,c?.first_name,c?.last_name,c?.email,c?.phone,c?.mobile,r.property_street,r.property_house_number,r.property_postal_code,r.property_city].filter(Boolean).join(" ").toLowerCase();
    if(q&&!hay.includes(q))return false; if(status!=="ALL"&&r.status!==status)return false; if(source!=="ALL"&&r.source_id!==source)return false; if(responsible!=="ALL"&&r.primary_responsible_user!==responsible)return false; if(followup==="OVERDUE"&&!(r.follow_up_at&&new Date(r.follow_up_at).getTime()<now))return false; if(followup==="OPEN"&&!r.follow_up_at)return false; return true;
  });
  const total=filtered.length,totalPages=Math.max(1,Math.ceil(total/pageSize)); filtered=filtered.slice((page-1)*pageSize,page*pageSize);
  const profileMap=Object.fromEntries((profiles??[]).map((p:any)=>[p.user_id,p.display_name]));
  return data({rows:filtered,sources:sources??[],profiles:profiles??[],profileMap,pipeline,profile,filters:{q,status,source,responsible,followup,archived,page},total,totalPages},{headers:responseHeaders()});
}

export default function Leads(){
  const {rows,sources,profiles,profileMap,pipeline,profile,filters,total,totalPages}=useLoaderData<typeof loader>();
  const pageHref=(page:number)=>{const p=new URLSearchParams(); if(filters.q)p.set("q",filters.q); if(filters.status!=="ALL")p.set("status",filters.status); if(filters.source!=="ALL")p.set("source",filters.source); if(filters.responsible!=="ALL")p.set("responsible",filters.responsible); if(filters.followup!=="ALL")p.set("followup",filters.followup); if(filters.archived)p.set("archived","1"); p.set("page",String(page)); return `?${p.toString()}`;};
  return <main className="editor-shell lead-shell">
    <header className="editor-header"><div><Link className="back-link" to="/crm">← CRM</Link><p className="eyebrow">Modul 03 · Eigentümer & Leads</p><h1 className="editor-title">Verkäufer-Leads</h1><p className="editor-meta">Interessenten für einen möglichen Verkaufs- oder Bewertungsauftrag</p></div><div className="header-user"><Link className="primary-button link-button" to="/leads/new">+ Lead</Link><span className="badge">STAGING</span><small>{profile.display_name}</small></div></header>
    <div className="lead-page-width">
      <section className="data-card"><div className="card-head"><div><p className="eyebrow">Was ist ein Lead?</p><h2>Potenzieller Auftrag</h2></div></div><p className="lead-explainer"><strong>Ein Lead ist noch keine Immobilie.</strong> Er steht für einen potenziellen Verkäufer oder Eigentümer, der sich z. B. wegen einer Bewertung oder eines Verkaufs meldet. Wird daraus ein Auftrag, kann der Lead später kontrolliert in eine Immobilie übernommen werden.</p></section>
      <section className="data-card"><div className="card-head"><div><p className="eyebrow">Pipeline</p><h2>Verkäufer-Pipeline</h2></div><p className="lead-pipeline-note">Klick auf eine Stufe filtert die Liste. Statuswechsel erfolgen in der Leadakte.</p></div><div className="lead-pipeline">{pipeline.map(stage=><Link key={stage.status} className={`lead-stage${filters.status===stage.status?" active":""}`} to={`?status=${stage.status}`}><span className="lead-stage-name">{STATUS_LABELS[stage.status]}</span><strong>{stage.count}</strong><small>{stage.overdue} überfällige Wiedervorlagen</small></Link>)}</div></section>
      <section className="data-card"><Form method="get" className="lead-filter-grid"><label><span>Suche</span><input name="q" defaultValue={filters.q} placeholder="Leadnummer, Kontakt, Telefon, E-Mail, Adresse"/></label><label><span>Status</span><select name="status" defaultValue={filters.status}><option value="ALL">Alle</option>{STATUS_ORDER.map(s=><option key={s} value={s}>{STATUS_LABELS[s]}</option>)}</select></label><label><span>Quelle</span><select name="source" defaultValue={filters.source}><option value="ALL">Alle</option>{sources.map((s:any)=><option key={s.id} value={s.id}>{s.label}</option>)}</select></label><label><span>Verantwortlich</span><select name="responsible" defaultValue={filters.responsible}><option value="ALL">Alle</option>{profiles.map((p:any)=><option key={p.user_id} value={p.user_id}>{p.display_name}</option>)}</select></label><label><span>Wiedervorlage</span><select name="followup" defaultValue={filters.followup}><option value="ALL">Alle</option><option value="OPEN">Mit Wiedervorlage</option><option value="OVERDUE">Überfällig</option></select></label><label className="checkbox-row"><input type="checkbox" name="archived" value="1" defaultChecked={filters.archived}/><span>Archiv anzeigen</span></label><button className="secondary-button" type="submit">Filtern</button></Form></section>
      <section className="data-card"><div className="card-head"><div><p className="eyebrow">Leads</p><h2>{total} Treffer</h2></div><Link className="subtle-link" to="/leads/new">Lead anlegen</Link></div><div className="data-list">{rows.map((r:any)=>{const c=one(r.contacts),src=one(r.lead_sources),overdue=r.follow_up_at&&new Date(r.follow_up_at).getTime()<Date.now(); return <Link className="data-row data-row-link lead-list-row" to={`/leads/${r.id}`} key={r.id}><div><strong>{c?`${c.first_name} ${c.last_name}`:"Kontakt"}</strong><small>{r.lead_number} · {src?.label??"Quelle offen"}</small></div><div><span className="lead-status-pill">{STATUS_LABELS[r.status]??r.status}</span><small>{profileMap[r.primary_responsible_user]??"—"}</small></div><div><strong>{address(r)||"Objektadresse offen"}</strong><small className={overdue?"lead-overdue":""}>Wiedervorlage {fmt(r.follow_up_at)}</small></div><div className="lead-row-secondary"><small>Angelegt {fmt(r.created_at)}</small><small>Geändert {fmt(r.updated_at)}</small></div><span>Öffnen →</span></Link>})}{rows.length===0?<p className="empty-state">Keine Leads in dieser Ansicht.</p>:null}</div>{totalPages>1?<div className="lead-pagination"><span>Seite {filters.page} von {totalPages}</span><div className="inline-actions">{filters.page>1?<Link className="secondary-button link-button" to={pageHref(filters.page-1)}>← Zurück</Link>:null}{filters.page<totalPages?<Link className="secondary-button link-button" to={pageHref(filters.page+1)}>Weiter →</Link>:null}</div></div>:null}</section>
    </div>
  </main>;
}
