import { data, Form, Link, redirect, useActionData, useLoaderData } from "react-router";
import type { Route } from "./+types/property-exposes";
import { requirePermission } from "~/lib/auth.server";
import "~/publication.css";

type ActionResult={error?:string};
const STATUS:Record<string,string>={DRAFT:"Entwurf",GENERATED:"PDF erzeugt",APPROVED:"Freigegeben",RELEASED:"Zur Verwendung freigegeben",ARCHIVED:"Archiviert"};
function formatDate(v:string|null){return v?new Intl.DateTimeFormat("de-DE",{dateStyle:"medium",timeStyle:"short",timeZone:"Europe/Berlin"}).format(new Date(v)):"—";}
function money(v:any){const n=Number(v);return Number.isFinite(n)?new Intl.NumberFormat("de-DE",{style:"currency",currency:"EUR"}).format(n):"—";}

export async function loader({request,context,params}:Route.LoaderArgs){
 const {supabase,responseHeaders,profile}=await requirePermission(request,context.cloudflare.env,"property.read");const propertyId=params.propertyId!;
 const [{data:canRead},{data:canWrite},{data:property},{data:exposes,error}]=await Promise.all([
  supabase.rpc("current_user_has_permission",{p_permission:"expose.read"}),supabase.rpc("current_user_has_permission",{p_permission:"expose.write"}),
  supabase.from("properties").select("id,property_number,internal_title,status").eq("id",propertyId).maybeSingle(),
  supabase.from("property_exposes").select("id,expose_number,version_number,status,title,price,publication_version_id,generated_at,approved_at,released_at,archived_at,updated_at").eq("property_id",propertyId).order("version_number",{ascending:false})
 ]);
 if(canRead!==true)throw new Response("Keine Berechtigung für Exposés.",{status:403,headers:responseHeaders()});if(!property)throw new Response("Immobilie nicht gefunden.",{status:404,headers:responseHeaders()});if(error)throw new Response("Exposés konnten nicht geladen werden.",{status:500,headers:responseHeaders()});
 return data({property,exposes:exposes??[],canWrite:canWrite===true,profile},{headers:responseHeaders()});
}

export async function action({request,context,params}:Route.ActionArgs){
 const {supabase,responseHeaders,userId}=await requirePermission(request,context.cloudflare.env,"expose.write");const propertyId=params.propertyId!;
 const [{data:property,error:propertyError},{data:publication},{data:address},{data:energy},{data:features},{data:media}]=await Promise.all([
  supabase.from("properties").select("*").eq("id",propertyId).maybeSingle(),supabase.from("property_publications").select("*").eq("property_id",propertyId).maybeSingle(),supabase.from("property_addresses").select("*").eq("property_id",propertyId).maybeSingle(),supabase.from("property_energy_data").select("*").eq("property_id",propertyId).maybeSingle(),supabase.from("property_features").select("*").eq("property_id",propertyId).order("label"),supabase.from("property_media").select("id,media_type,title,sort_order").eq("property_id",propertyId).is("archived_at",null).order("sort_order")
 ]);
 if(propertyError||!property)return data<ActionResult>({error:"Immobilie nicht gefunden."},{status:404,headers:responseHeaders()});
 let approvedVersion:any=null;if(publication){const {data:v}=await supabase.from("property_publication_versions").select("id,version_number,public_title,teaser,snapshot,approved_at").eq("publication_id",publication.id).not("approved_at","is",null).order("version_number",{ascending:false}).limit(1).maybeSingle();approvedVersion=v;}
 const snap:any=approvedVersion?.snapshot??{};const publicAddress=snap.address??(address?{street:address.public_address_mode==='FULL'?address.street:null,house_number:address.public_address_mode==='FULL'?address.house_number:null,postal_code:address.postal_code,city:address.city,district:address.district,country:address.country}:{});
 const mappedFeatures=(features??[]).map((f:any)=>({key:f.feature_key,label:f.label,type:f.value_type,value:f.value_type==='BOOLEAN'?f.boolean_value:f.value_type==='NUMBER'?f.number_value:f.text_value,unit:f.unit}));
 const facts={property_number:property.property_number,property_type:property.property_type,transaction_type:property.transaction_type,living_area_sqm:property.living_area_sqm,usable_area_sqm:property.usable_area_sqm,plot_area_sqm:property.plot_area_sqm,rooms:property.rooms,bedrooms:property.bedrooms,bathrooms:property.bathrooms,floor:property.floor,year_built:property.year_built,modernization_year:property.modernization_year,condition:property.condition,available_from:property.available_from,parking_spaces:property.parking_spaces,residential_units:property.residential_units,address:publicAddress,features:snap.features??mappedFeatures,highlights:snap.highlights??publication?.public_highlights??[]};
 const energyData=snap.energy??(energy?{certificate_present:energy.certificate_present,certificate_type:energy.certificate_type,energy_value_kwh:energy.energy_value_kwh,efficiency_class:energy.efficiency_class,energy_source:energy.energy_source,building_year:energy.building_year,valid_until:energy.valid_until}:{});
 const sourceSnapshot={property_id:property.id,property_number:property.property_number,property_version:property.version,publication_version_id:approvedVersion?.id??null,publication_version_number:approvedVersion?.version_number??null,imported_at:new Date().toISOString()};
 const {data:created,error}=await supabase.from("property_exposes").insert({property_id:propertyId,publication_version_id:approvedVersion?.id??null,status:"DRAFT",generator_version:2,title:approvedVersion?.public_title??publication?.public_title??property.internal_title,subtitle:snap.subtitle??publication?.subtitle??null,short_description:approvedVersion?.teaser??publication?.teaser??null,long_description:snap.description??publication?.description??null,features_description:snap.features_description??publication?.features_description??null,location_description:snap.location_description??publication?.location_description??null,other_information:null,price:snap.price??(property.transaction_type==='SALE'?property.purchase_price:property.rent_cold),currency:"EUR",facts,energy:energyData,source_snapshot:sourceSnapshot,source_property_version:property.version,created_by:userId,updated_by:userId}).select("id").single();
 if(error||!created)return data<ActionResult>({error:"Exposé-Entwurf konnte nicht angelegt werden."},{status:400,headers:responseHeaders()});
 const images=(media??[]).filter((m:any)=>m.media_type==='IMAGE'),plans=(media??[]).filter((m:any)=>m.media_type==='FLOOR_PLAN');const relations:any[]=[];if(images[0])relations.push({expose_id:created.id,media_id:images[0].id,role:"COVER",sort_order:0,created_by:userId,updated_by:userId});images.slice(1).forEach((m:any,i:number)=>relations.push({expose_id:created.id,media_id:m.id,role:"GALLERY",sort_order:i,created_by:userId,updated_by:userId}));plans.forEach((m:any,i:number)=>relations.push({expose_id:created.id,media_id:m.id,role:"FLOOR_PLAN",sort_order:i,created_by:userId,updated_by:userId}));if(relations.length)await supabase.from("property_expose_media").insert(relations);
 return redirect(`/properties/${propertyId}/exposes/${created.id}`,{headers:responseHeaders()});
}

export default function PropertyExposes(){const {property,exposes,canWrite,profile}=useLoaderData<typeof loader>();const result=useActionData<typeof action>();return <main className="editor-shell"><header className="editor-header"><div><Link className="back-link" to={`/properties/${property.id}`}>← Objektakte</Link><p className="eyebrow">Modul 05 · Exposés</p><h1 className="editor-title">Exposés</h1><p className="editor-meta">{property.property_number} · {property.internal_title}</p></div><div className="header-actions">{canWrite?<Form method="post"><button className="primary-button" type="submit">+ Exposé-Version anlegen</button></Form>:null}<span className="badge">{__APP_ENV_LABEL__}</span><small>{profile.display_name}</small></div></header>{result?.error?<div className="form-error">{result.error}</div>:null}<section className="data-card"><div className="card-head"><div><p className="eyebrow">Arbeitsweise</p><h2>Bearbeiten → Vorschau → PDF → Freigabe</h2></div></div><p>Neue Versionen übernehmen vorhandene Objekt- und Vermarktungsdaten als editierbaren Ausgangspunkt. Nach der PDF-Erzeugung bleibt der Inhalt dieser Version unverändert; spätere Änderungen erfolgen in einer neuen Exposé-Version.</p></section><section className="data-card"><div className="card-head"><div><p className="eyebrow">Versionen</p><h2>{exposes.length} Exposé-Versionen</h2></div></div><div className="data-list">{exposes.map((e:any)=><Link className="data-row data-row-link" to={`/properties/${property.id}/exposes/${e.id}`} key={e.id}><div><strong>{e.expose_number} · Version {e.version_number}</strong><small>{e.title??"Titel noch offen"} · {money(e.price)}</small></div><div className="row-meta"><span className={`status-pill ${e.status==='RELEASED'?'status-sold':e.status==='APPROVED'?'status-marketing':e.status==='DRAFT'?'status-draft':'status-preparation'}`}>{STATUS[e.status]??e.status}</span><small>aktualisiert {formatDate(e.updated_at)}</small></div><span className="subtle-link">Öffnen →</span></Link>)}{exposes.length===0?<p className="empty-state">Noch kein Exposé vorhanden. Lege die erste Version aus den aktuellen Objektdaten an.</p>:null}</div></section></main>}
