import { data, Link, useLoaderData } from "react-router";
import type { Route } from "./+types/property-publication-preview";
import { requirePermission } from "~/lib/auth.server";
import "~/public-website.css";

const TYPE_LABELS:Record<string,string>={DETACHED_HOUSE:"Einfamilienhaus",SEMI_DETACHED_HOUSE:"Doppelhaushälfte",TERRACED_HOUSE:"Reihenhaus",APARTMENT_BUILDING:"Mehrfamilienhaus",APARTMENT:"Wohnung",PENTHOUSE:"Penthouse",MAISONETTE:"Maisonette",LAND:"Grundstück",COMMERCIAL:"Gewerbe",OFFICE:"Büro",RETAIL:"Einzelhandel",GARAGE:"Garage",PARKING_SPACE:"Stellplatz",OTHER:"Immobilie"};
function money(v:any){return v===null||v===undefined?"Preis auf Anfrage":new Intl.NumberFormat("de-DE",{style:"currency",currency:"EUR",maximumFractionDigits:0}).format(Number(v));}
function addressLabel(s:any){const a=s.address;if(!a)return"Adresse auf Anfrage";const street=[a.street,a.house_number].filter(Boolean).join(" ");const city=[a.postal_code,a.city].filter(Boolean).join(" ");return [street,city,a.district].filter(Boolean).join(" · ")||"Adresse auf Anfrage";}
function mediaUrl(item:any){return item?.id&&item?.source_version?`/immobilien/medien/${item.id}/${item.source_version}`:null;}
export function meta(){return[{title:"Publikationsvorschau · ZeyherMutterOS"},{name:"robots",content:"noindex,nofollow"}]}
export async function loader({request,context,params}:Route.LoaderArgs){const {supabase,responseHeaders}=await requirePermission(request,context.cloudflare.env,"property.read");const propertyId=params.propertyId!;const {data:publication,error}=await supabase.from("property_publications").select("id,candidate_version,status").eq("property_id",propertyId).maybeSingle();if(error||!publication||publication.status!=="READY"||!publication.candidate_version)throw new Response("Keine vorbereitete Version vorhanden.",{status:404,headers:responseHeaders()});const {data:version,error:versionError}=await supabase.from("property_publication_versions").select("version_number,public_title,teaser,snapshot").eq("publication_id",publication.id).eq("version_number",publication.candidate_version).maybeSingle();if(versionError||!version)throw new Response("Vorschauversion nicht gefunden.",{status:404,headers:responseHeaders()});return data({propertyId,version},{headers:responseHeaders()});}
export default function PublicationPreview(){const {propertyId,version}=useLoaderData<typeof loader>();const s:any=version.snapshot??{},media=s.media??[],features=(s.features??[]).filter((f:any)=>f.type!=="BOOLEAN"||f.value===true);return <main className="public-site"><div className="public-preview-banner">Interne Vorschau · Version {version.version_number} · noch nicht öffentlich</div><header className="public-header"><Link className="public-brand" to={`/properties/${propertyId}/publication`}><span>ZM</span><strong>ZeyherMutter</strong></Link><Link className="public-back" to={`/properties/${propertyId}/publication`}>← Zur Veröffentlichungsakte</Link></header><section className="public-detail-hero"><div><p className="public-eyebrow">{s.transaction_type==="RENT"?"Zur Miete":"Zum Kauf"} · {TYPE_LABELS[s.property_type]??"Immobilie"}</p><h1>{version.public_title}</h1>{s.subtitle?<p className="public-subtitle">{s.subtitle}</p>:null}<p className="public-detail-lead">{version.teaser||s.location_description||addressLabel(s)}</p></div><div className="public-price"><strong>{money(s.price)}</strong><span>{addressLabel(s)}</span></div></section>{media.length?<section className={`public-gallery ${media.length===1?"single":""}`}>{media.map((item:any,index:number)=>{const url=mediaUrl(item);return url?<figure className={index===0?"public-gallery-main":"public-gallery-item"} key={`${item.id}-${item.source_version}`}><img src={url} alt={item.alt_text||item.title||`Vorschaubild ${index+1}`}/>{item.title?<figcaption>{item.title}</figcaption>:null}</figure>:null})}</section>:null}<section className="public-fact-grid"><div><span>Wohnfläche</span><strong>{s.living_area_sqm?`${Number(s.living_area_sqm)} m²`:"—"}</strong></div><div><span>Zimmer</span><strong>{s.rooms?Number(s.rooms):"—"}</strong></div><div><span>Grundstück</span><strong>{s.plot_area_sqm?`${Number(s.plot_area_sqm)} m²`:"—"}</strong></div><div><span>Baujahr</span><strong>{s.year_built??"—"}</strong></div></section><section className="public-detail-grid"><article><p className="public-eyebrow">Objekt</p><h2>Beschreibung</h2><div className="public-prose">{String(s.description??"").split("\n").map((p:string,i:number)=>p?<p key={i}>{p}</p>:null)}</div>{s.features_description?<><h3>Ausstattung</h3><p>{s.features_description}</p></>:null}</article><aside>{s.location_description?<div className="public-side-card"><p className="public-eyebrow">Lage</p><h3>Umgebung</h3><p>{s.location_description}</p></div>:null}<div className="public-side-card"><p className="public-eyebrow">Merkmale</p><h3>Ausstattung</h3>{features.length?<ul>{features.slice(0,18).map((f:any)=><li key={f.key}>{f.label}</li>)}</ul>:<p>Keine zusätzlichen Merkmale.</p>}</div></aside></section></main>}
