import { data, Form, redirect, useActionData, useLoaderData } from "react-router";
import type { Route } from "./+types/public-contact";
import { ContactIntroSections, ContactPersonal } from "~/components/public-page-sections";
import { PublicFooter, PublicHeader } from "~/components/public-shell";
import { loadPublicWebsitePage } from "~/lib/website-content.server";
import { createSupabaseServerClient } from "~/lib/supabase.server";
import "~/public-website.css";

function clean(fd:FormData,key:string,max:number){return String(fd.get(key)??"").trim().replace(/\s+/g," ").slice(0,max);}
async function sha256(value:string){const bytes=new TextEncoder().encode(value);const hash=await crypto.subtle.digest("SHA-256",bytes);return Array.from(new Uint8Array(hash)).map(v=>v.toString(16).padStart(2,"0")).join("");}
export function meta({data:loaderData}:Route.MetaArgs){return[{title:loaderData?.seoTitle??"Kontakt · ZeyherMutter"},{name:"description",content:loaderData?.seoDescription??"Kontaktieren Sie ZeyherMutter für Ihre Immobilienanfrage."}]}
export async function loader({request,context}:Route.LoaderArgs){const submitted=new URL(request.url).searchParams.get("anfrage")==="gesendet";const page=await loadPublicWebsitePage(request,context.cloudflare.env,"CONTACT");return data({...page,submitted},{headers:{"Cache-Control":submitted?"private, no-store":"public, max-age=60, stale-while-revalidate=300"}});}
export async function action({request,context}:Route.ActionArgs){const fd=await request.formData();const company=clean(fd,"company",120);if(company)return redirect("/kontakt?anfrage=gesendet#formular",{headers:{"Cache-Control":"private, no-store"}});const firstName=clean(fd,"first_name",100),lastName=clean(fd,"last_name",100),email=clean(fd,"email",254).toLowerCase(),phone=clean(fd,"phone",60),message=clean(fd,"message",4000),consent=fd.get("consent")==="on";if(!firstName||!lastName||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||message.length<10||!consent)return data({error:"Bitte füllen Sie alle Pflichtfelder vollständig aus und bestätigen Sie die Einwilligung."},{status:400,headers:{"Cache-Control":"private, no-store"}});const timeBucket=Math.floor(Date.now()/(5*60*1000));const submissionKey=await sha256(`GENERAL|${email}|${message}|${timeBucket}`);const {supabase}=createSupabaseServerClient(request,context.cloudflare.env);const sourceUrl=new URL(request.url);sourceUrl.search="";sourceUrl.hash="";const {data:result,error}=await supabase.functions.invoke("website-inquiry",{body:{kind:"GENERAL",first_name:firstName,last_name:lastName,email,phone,message,consent:true,company:"",submission_key:submissionKey,source_url:sourceUrl.toString()}});if(error||!result?.ok){const isRate=result?.error==="RATE_LIMIT";return data({error:isRate?"Es wurden in kurzer Zeit bereits mehrere Anfragen gesendet. Bitte versuchen Sie es später erneut.":"Ihre Anfrage konnte gerade nicht gesendet werden. Bitte versuchen Sie es erneut."},{status:isRate?429:503,headers:{"Cache-Control":"private, no-store"}});}return redirect("/kontakt?anfrage=gesendet#formular",{headers:{"Cache-Control":"private, no-store"}});}
export default function PublicContact(){const {submitted,content}=useLoaderData<typeof loader>();const result=useActionData<typeof action>();return <main className="public-site"><PublicHeader/><ContactIntroSections content={content}/><section className="public-contact-page" id="formular"><ContactPersonal content={content}/><div className="public-contact-form-card">{submitted?<div className="public-form-success"><strong>{content.success_title}</strong><span>{content.success_text}</span></div>:<>{result?.error?<div className="public-form-message">{result.error}</div>:null}<Form method="post" className="public-inquiry-form"><div className="public-form-grid"><label><span>Vorname *</span><input name="first_name" required autoComplete="given-name"/></label><label><span>Nachname *</span><input name="last_name" required autoComplete="family-name"/></label></div><div className="public-form-grid"><label><span>E-Mail *</span><input name="email" type="email" required autoComplete="email"/></label><label><span>Telefon</span><input name="phone" type="tel" autoComplete="tel"/></label></div><label><span>Nachricht *</span><textarea name="message" rows={6} minLength={10} maxLength={4000} required/></label><label className="public-honeypot" aria-hidden="true"><span>Firma</span><input name="company" tabIndex={-1} autoComplete="off"/></label><label className="public-consent light"><input type="checkbox" name="consent" required/><span>{content.consent_text}</span></label><button className="public-primary-button dark" type="submit">{content.submit_label}</button></Form></>}</div></section><PublicFooter/></main>}
