import { data, Form, Link, useActionData, useLoaderData } from "react-router";
import type { Route } from "./+types/public-property-detail";
import { createSupabaseServerClient } from "~/lib/supabase.server";
import "~/public-website.css";

const TYPE_LABELS:Record<string,string>={DETACHED_HOUSE:"Einfamilienhaus",SEMI_DETACHED_HOUSE:"Doppelhaushälfte",TERRACED_HOUSE:"Reihenhaus",APARTMENT_BUILDING:"Mehrfamilienhaus",APARTMENT:"Wohnung",PENTHOUSE:"Penthouse",MAISONETTE:"Maisonette",LAND:"Grundstück",COMMERCIAL:"Gewerbe",OFFICE:"Büro",RETAIL:"Einzelhandel",GARAGE:"Garage",PARKING_SPACE:"Stellplatz",OTHER:"Immobilie"};
function money(v:any){return v===null||v===undefined?"Preis auf Anfrage":new Intl.NumberFormat("de-DE",{style:"currency",currency:"EUR",maximumFractionDigits:0}).format(Number(v));}
function addressLabel(s:any){const a=s.address;if(!a)return"Adresse auf Anfrage";const street=[a.street,a.house_number].filter(Boolean).join(" ");const city=[a.postal_code,a.city].filter(Boolean).join(" ");return [street,city,a.district].filter(Boolean).join(" · ")||"Adresse auf Anfrage";}
function mediaUrl(item:any){return item?.id&&item?.source_version?`/immobilien/medien/${item.id}/${item.source_version}`:null;}
function formatDate(value:any){if(!value)return"Auf Anfrage";try{return new Intl.DateTimeFormat("de-DE",{dateStyle:"medium",timeZone:"Europe/Berlin"}).format(new Date(value));}catch{return String(value);}}
export function meta({data:routeData}:Route.MetaArgs){const row=(routeData as any)?.row,s=row?.snapshot??{};return[{title:`${s.seo?.title||row?.public_title||"Immobilie"} · ZeyherMutter`},{name:"description",content:s.seo?.description||row?.teaser||"Immobilienangebot von ZeyherMutter"},{name:"robots",content:"index,follow"}]}
export async function loader({request,context,params}:Route.LoaderArgs){const {supabase}=createSupabaseServerClient(request,context.cloudflare.env);const {data:rows,error}=await supabase.rpc("public_property_by_slug",{p_slug:params.slug!});if(error)throw new Response("Immobilie konnte nicht geladen werden.",{status:500});const row=rows?.[0];if(!row)throw new Response("Immobilie nicht gefunden.",{status:404,headers:{"Cache-Control":"public, max-age=30"}});return data({row},{headers:{"Cache-Control":"public, max-age=60, s-maxage=120"}});}
export async function action(){return data({error:"Das Anfrageformular wird gerade mit dem CRM verbunden."},{status:503});}
export default function PublicPropertyDetail(){const {row}=useLoaderData<typeof loader>();const result=useActionData<typeof action>();const s:any=row.snapshot??{},features=(s.features??[]).filter((f:any)=>f.type!=="BOOLEAN"||f.value===true),highlights=s.highlights??[],media=s.media??[];return <main className="public-site"><header className="public-header"><Link className="public-brand" to="/immobilien"><span>ZM</span><strong>ZeyherMutter</strong></Link><nav className="public-nav"><Link to="/immobilien">Immobilien</Link><Link to="/kontakt">Kontakt</Link></nav></header>
 <section className="public-detail-hero"><div><p className="public-eyebrow">{s.transaction_type==="RENT"?"Zur Miete":"Zum Kauf"} · {TYPE_LABELS[s.property_type]??"Immobilie"}</p><h1>{row.public_title}</h1>{s.subtitle?<p className="public-subtitle">{s.subtitle}</p>:null}<p className="public-detail-lead">{row.teaser||s.location_description||addressLabel(s)}</p></div><div className="public-price"><strong>{money(s.price)}</strong><span>{addressLabel(s)}</span></div></section>
 {media.length?<section className={`public-gallery ${media.length===1?"single":""}`}>{media.map((item:any,index:number)=>{const url=mediaUrl(item);return url?<figure className={index===0?"public-gallery-main":"public-gallery-item"} key={`${item.id}-${item.source_version}`}><img src={url} alt={item.alt_text||item.title||`${row.public_title} – Bild ${index+1}`}/>{item.title?<figcaption>{item.title}</figcaption>:null}</figure>:null})}</section>:null}
 <section className="public-fact-grid"><div><span>Wohnfläche</span><strong>{s.living_area_sqm?`${Number(s.living_area_sqm)} m²`:"—"}</strong></div><div><span>Zimmer</span><strong>{s.rooms?Number(s.rooms):"—"}</strong></div><div><span>Grundstück</span><strong>{s.plot_area_sqm?`${Number(s.plot_area_sqm)} m²`:"—"}</strong></div><div><span>Baujahr</span><strong>{s.year_built??"—"}</strong></div></section>
 <section className="public-detail-grid"><article><p className="public-eyebrow">Objekt</p><h2>Beschreibung</h2><div className="public-prose">{String(s.description??"").split("\n").map((p:string,i:number)=>p?<p key={i}>{p}</p>:null)}</div>{highlights.length?<><h3>Highlights</h3><ul className="public-highlights">{highlights.map((h:string)=><li key={h}>{h}</li>)}</ul></>:null}{s.features_description?<><h3>Ausstattung</h3><div className="public-prose">{String(s.features_description).split("\n").map((p:string,i:number)=>p?<p key={i}>{p}</p>:null)}</div></>:null}</article><aside>
  <div className="public-side-card"><p className="public-eyebrow">Eckdaten</p><h3>{TYPE_LABELS[s.property_type]??"Immobilie"}</h3><dl className="public-definition-list"><div><dt>Referenz</dt><dd>{s.property_number??"—"}</dd></div><div><dt>Verfügbar</dt><dd>{formatDate(s.available_from)}</dd></div>{s.usable_area_sqm?<div><dt>Nutzfläche</dt><dd>{Number(s.usable_area_sqm)} m²</dd></div>:null}{s.bathrooms?<div><dt>Bäder</dt><dd>{s.bathrooms}</dd></div>:null}{s.parking_spaces?<div><dt>Stellplätze</dt><dd>{s.parking_spaces}</dd></div>:null}</dl></div>
  {s.location_description?<div className="public-side-card"><p className="public-eyebrow">Lage</p><h3>Umgebung</h3><p>{s.location_description}</p></div>:null}
  <div className="public-side-card"><p className="public-eyebrow">Merkmale</p><h3>Ausstattung</h3>{features.length?<ul>{features.slice(0,18).map((f:any)=><li key={f.key}>{f.label}{f.type!=="BOOLEAN"&&f.value!==null?`: ${String(f.value)}${f.unit?` ${f.unit}`:""}`:""}</li>)}</ul>:<p>Weitere Merkmale auf Anfrage.</p>}</div>
  {s.energy?<div className="public-side-card"><p className="public-eyebrow">Energie</p><h3>Energiedaten</h3><dl className="public-definition-list">{s.energy.efficiency_class?<div><dt>Effizienzklasse</dt><dd>{s.energy.efficiency_class}</dd></div>:null}{s.energy.energy_value_kwh?<div><dt>Endenergie</dt><dd>{Number(s.energy.energy_value_kwh)} kWh/(m²·a)</dd></div>:null}{s.energy.energy_source?<div><dt>Energieträger</dt><dd>{s.energy.energy_source}</dd></div>:null}</dl></div>:null}
 </aside></section>
 <section className="public-contact-cta" id="anfrage"><p className="public-eyebrow">Interesse?</p><h2>Diese Immobilie anfragen.</h2><p>Ihre Anfrage wird direkt dem Objekt zugeordnet und von ZeyherMutter persönlich bearbeitet.</p>{result?.error?<div className="public-form-message">{result.error}</div>:null}<Form method="post" className="public-inquiry-form"><div className="public-form-grid"><label><span>Vorname *</span><input name="first_name" required autoComplete="given-name"/></label><label><span>Nachname *</span><input name="last_name" required autoComplete="family-name"/></label></div><div className="public-form-grid"><label><span>E-Mail *</span><input name="email" type="email" required autoComplete="email"/></label><label><span>Telefon</span><input name="phone" type="tel" autoComplete="tel"/></label></div><label><span>Nachricht *</span><textarea name="message" rows={5} required defaultValue={`Guten Tag, ich interessiere mich für ${row.public_title}.`}/></label><label className="public-honeypot" aria-hidden="true"><span>Firma</span><input name="company" tabIndex={-1} autoComplete="off"/></label><label className="public-consent"><input type="checkbox" name="consent" required/><span>Ich stimme zu, dass meine Angaben zur Bearbeitung dieser Anfrage gespeichert und verarbeitet werden. *</span></label><button className="public-primary-button" type="submit">Anfrage senden</button></Form></section>
 <footer className="public-footer"><span>ZeyherMutter · Immobilienvermittlung</span><div><Link to="/impressum">Impressum</Link><Link to="/datenschutz">Datenschutz</Link></div></footer></main>}
