import { data, Link, useLoaderData } from "react-router";
import type { Route } from "./+types/public-properties";
import { createSupabaseServerClient } from "~/lib/supabase.server";
import "~/public-website.css";

const TYPE_LABELS:Record<string,string>={DETACHED_HOUSE:"Einfamilienhaus",SEMI_DETACHED_HOUSE:"Doppelhaushälfte",TERRACED_HOUSE:"Reihenhaus",APARTMENT_BUILDING:"Mehrfamilienhaus",APARTMENT:"Wohnung",PENTHOUSE:"Penthouse",MAISONETTE:"Maisonette",LAND:"Grundstück",COMMERCIAL:"Gewerbe",OFFICE:"Büro",RETAIL:"Einzelhandel",GARAGE:"Garage",PARKING_SPACE:"Stellplatz",OTHER:"Immobilie"};
function money(v:any){return v===null||v===undefined?"Preis auf Anfrage":new Intl.NumberFormat("de-DE",{style:"currency",currency:"EUR",maximumFractionDigits:0}).format(Number(v));}
function mediaUrl(item:any){return item?.id&&item?.source_version?`/immobilien/medien/${item.id}/${item.source_version}`:null;}
function locationLabel(s:any){const a=s.address??{};return [a.postal_code,a.city,a.district].filter(Boolean).join(" · ")||"Lage auf Anfrage";}
export function meta(){return[{title:"Immobilien · ZeyherMutter"},{name:"description",content:"Aktuell veröffentlichte Immobilien von ZeyherMutter."}]}
export async function loader({request,context}:Route.LoaderArgs){const {supabase}=createSupabaseServerClient(request,context.cloudflare.env);const {data:rows,error}=await supabase.rpc("public_property_listings");if(error)throw new Response("Immobilien konnten nicht geladen werden.",{status:500});return data({rows:rows??[]},{headers:{"Cache-Control":"public, max-age=60, s-maxage=120"}});}
export default function PublicProperties(){const {rows}=useLoaderData<typeof loader>();return <main className="public-site"><header className="public-header"><Link className="public-brand" to="/immobilien"><span>ZM</span><strong>ZeyherMutter</strong></Link><nav className="public-nav"><Link to="/immobilien">Immobilien</Link><Link to="/kontakt">Kontakt</Link></nav></header><section className="public-hero"><p className="public-eyebrow">Immobilien</p><h1>Aktuelle Angebote.</h1><p>Ausgewählte Immobilien, die derzeit von ZeyherMutter veröffentlicht sind.</p></section><section className="public-property-grid">{rows.map((row:any)=>{const s=row.snapshot??{},media=s.media??[],main=media[0],image=mediaUrl(main);return <Link className="public-property-card" key={row.public_slug} to={`/immobilien/${row.public_slug}`}>{image?<div className="public-property-image-wrap"><img className="public-property-image" src={image} alt={main.alt_text||main.title||row.public_title}/><span>{TYPE_LABELS[s.property_type]??"Immobilie"}</span></div>:<div className="public-property-placeholder"><span>{TYPE_LABELS[s.property_type]??"Immobilie"}</span></div>}<div className="public-property-card-body"><p className="public-eyebrow">{s.transaction_type==="RENT"?"Zur Miete":"Zum Kauf"} · {locationLabel(s)}</p><h2>{row.public_title}</h2><p>{row.teaser||s.location_description||"Weitere Informationen zum Objekt."}</p><div className="public-property-facts"><strong>{money(s.price)}</strong><span>{s.living_area_sqm?`${Number(s.living_area_sqm)} m²`:s.plot_area_sqm?`${Number(s.plot_area_sqm)} m² Grundstück`:""}{s.rooms?` · ${Number(s.rooms)} Zimmer`:""}</span></div></div></Link>})}{rows.length===0?<div className="public-empty"><h2>Aktuell keine veröffentlichten Immobilien.</h2><p>Neue Angebote erscheinen hier nach ihrer Freigabe automatisch.</p></div>:null}</section><footer className="public-footer"><span>ZeyherMutter · Immobilienvermittlung</span><div><Link to="/impressum">Impressum</Link><Link to="/datenschutz">Datenschutz</Link></div></footer></main>}
