import { data, Link, useLoaderData } from "react-router";
import type { Route } from "./+types/public-property-detail";
import { createSupabaseServerClient } from "~/lib/supabase.server";
import "~/public-website.css";

const TYPE_LABELS:Record<string,string>={DETACHED_HOUSE:"Einfamilienhaus",SEMI_DETACHED_HOUSE:"Doppelhaushälfte",TERRACED_HOUSE:"Reihenhaus",APARTMENT_BUILDING:"Mehrfamilienhaus",APARTMENT:"Wohnung",PENTHOUSE:"Penthouse",MAISONETTE:"Maisonette",LAND:"Grundstück",COMMERCIAL:"Gewerbe",OFFICE:"Büro",RETAIL:"Einzelhandel",GARAGE:"Garage",PARKING_SPACE:"Stellplatz",OTHER:"Immobilie"};
function money(v:any){return v===null||v===undefined?"Preis auf Anfrage":new Intl.NumberFormat("de-DE",{style:"currency",currency:"EUR",maximumFractionDigits:0}).format(Number(v));}
function addressLabel(s:any){const a=s.address;if(!a)return"Adresse auf Anfrage";return [a.street,a.house_number,a.postal_code,a.city,a.district].filter(Boolean).join(" ");}
export function meta({data:routeData}:Route.MetaArgs){const row=(routeData as any)?.row,s=row?.snapshot??{};return[{title:`${s.seo?.title||row?.public_title||"Immobilie"} · ZeyherMutter`},{name:"description",content:s.seo?.description||row?.teaser||"Immobilienangebot von ZeyherMutter"}]}
export async function loader({request,context,params}:Route.LoaderArgs){const {supabase}=createSupabaseServerClient(request,context.cloudflare.env);const {data:rows,error}=await supabase.rpc("public_property_by_slug",{p_slug:params.slug!});if(error)throw new Response("Immobilie konnte nicht geladen werden.",{status:500});const row=rows?.[0];if(!row)throw new Response("Immobilie nicht gefunden.",{status:404});return data({row},{headers:{"Cache-Control":"public, max-age=60, s-maxage=120"}});}
export default function PublicPropertyDetail(){const {row}=useLoaderData<typeof loader>();const s:any=row.snapshot??{},features=(s.features??[]).filter((f:any)=>f.type!=="BOOLEAN"||f.value===true),highlights=s.highlights??[];return <main className="public-site"><header className="public-header"><Link className="public-brand" to="/immobilien"><span>ZM</span><strong>ZeyherMutter</strong></Link><Link className="public-back" to="/immobilien">← Alle Immobilien</Link></header><section className="public-detail-hero"><div><p className="public-eyebrow">{s.transaction_type==="RENT"?"Zur Miete":"Zum Kauf"} · {TYPE_LABELS[s.property_type]??"Immobilie"}</p><h1>{row.public_title}</h1><p className="public-detail-lead">{row.teaser||s.location_description||addressLabel(s)}</p></div><div className="public-price"><strong>{money(s.price)}</strong><span>{addressLabel(s)}</span></div></section><section className="public-fact-grid"><div><span>Wohnfläche</span><strong>{s.living_area_sqm?`${Number(s.living_area_sqm)} m²`:"—"}</strong></div><div><span>Zimmer</span><strong>{s.rooms?Number(s.rooms):"—"}</strong></div><div><span>Grundstück</span><strong>{s.plot_area_sqm?`${Number(s.plot_area_sqm)} m²`:"—"}</strong></div><div><span>Baujahr</span><strong>{s.year_built??"—"}</strong></div></section><section className="public-detail-grid"><article><p className="public-eyebrow">Objekt</p><h2>Beschreibung</h2><div className="public-prose">{String(s.description??"").split("\n").map((p:string,i:number)=>p?<p key={i}>{p}</p>:null)}</div>{highlights.length?<><h3>Highlights</h3><ul className="public-highlights">{highlights.map((h:string)=><li key={h}>{h}</li>)}</ul></>:null}</article><aside>{s.location_description?<div className="public-side-card"><p className="public-eyebrow">Lage</p><h3>Umgebung</h3><p>{s.location_description}</p></div>:null}<div className="public-side-card"><p className="public-eyebrow">Ausstattung</p><h3>Merkmale</h3>{features.length?<ul>{features.slice(0,14).map((f:any)=><li key={f.key}>{f.label}{f.type!=="BOOLEAN"&&f.value!==null?`: ${String(f.value)}${f.unit?` ${f.unit}`:""}`:""}</li>)}</ul>:<p>Weitere Merkmale auf Anfrage.</p>}</div>{s.energy?<div className="public-side-card"><p className="public-eyebrow">Energie</p><h3>Energiedaten</h3><p>{s.energy.efficiency_class?`Klasse ${s.energy.efficiency_class}`:"Energieausweis vorhanden"}{s.energy.energy_value_kwh?` · ${Number(s.energy.energy_value_kwh)} kWh/(m²·a)`:""}</p></div>:null}</aside></section><section className="public-contact-cta"><p className="public-eyebrow">Interesse?</p><h2>Wir freuen uns auf Ihre Anfrage.</h2><p>Die direkte Website-Anfrage wird als nächster Modul‑05-Schritt mit dem bereits vorhandenen Anfrageprozess aus Modul 04 verbunden.</p></section><footer className="public-footer">ZeyherMutter · Immobilienvermittlung</footer></main>}
