import { data, Form, Link, redirect, useActionData, useLoaderData } from "react-router";
import type { Route } from "./+types/public-contact";
import { createSupabaseServerClient } from "~/lib/supabase.server";
import "~/public-website.css";

function clean(fd:FormData,key:string,max:number){return String(fd.get(key)??"").trim().replace(/\s+/g," ").slice(0,max);}
async function sha256(value:string){const bytes=new TextEncoder().encode(value);const hash=await crypto.subtle.digest("SHA-256",bytes);return Array.from(new Uint8Array(hash)).map(v=>v.toString(16).padStart(2,"0")).join("");}
export function meta(){return[{title:"Kontakt · ZeyherMutter"},{name:"description",content:"Kontaktieren Sie ZeyherMutter für Ihre Immobilienanfrage."}]}
export async function loader({request}:Route.LoaderArgs){const submitted=new URL(request.url).searchParams.get("anfrage")==="gesendet";return data({submitted},{headers:{"Cache-Control":submitted?"private, no-store":"public, max-age=300"}});}
export async function action({request,context}:Route.ActionArgs){const fd=await request.formData();const company=clean(fd,"company",120);if(company)return redirect("/kontakt?anfrage=gesendet#formular",{headers:{"Cache-Control":"private, no-store"}});const firstName=clean(fd,"first_name",100),lastName=clean(fd,"last_name",100),email=clean(fd,"email",254).toLowerCase(),phone=clean(fd,"phone",60),message=clean(fd,"message",4000),consent=fd.get("consent")==="on";if(!firstName||!lastName||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||message.length<10||!consent)return data({error:"Bitte füllen Sie alle Pflichtfelder vollständig aus und bestätigen Sie die Einwilligung."},{status:400,headers:{"Cache-Control":"private, no-store"}});const timeBucket=Math.floor(Date.now()/(5*60*1000));const submissionKey=await sha256(`GENERAL|${email}|${message}|${timeBucket}`);const {supabase}=createSupabaseServerClient(request,context.cloudflare.env);const sourceUrl=new URL(request.url);sourceUrl.search="";sourceUrl.hash="";const {data:result,error}=await supabase.functions.invoke("website-inquiry",{body:{kind:"GENERAL",first_name:firstName,last_name:lastName,email,phone,message,consent:true,company:"",submission_key:submissionKey,source_url:sourceUrl.toString()}});if(error||!result?.ok){const isRate=result?.error==="RATE_LIMIT";return data({error:isRate?"Es wurden in kurzer Zeit bereits mehrere Anfragen gesendet. Bitte versuchen Sie es später erneut.":"Ihre Anfrage konnte gerade nicht gesendet werden. Bitte versuchen Sie es erneut."},{status:isRate?429:503,headers:{"Cache-Control":"private, no-store"}});}return redirect("/kontakt?anfrage=gesendet#formular",{headers:{"Cache-Control":"private, no-store"}});}
export default function PublicContact(){const {submitted}=useLoaderData<typeof loader>();const result=useActionData<typeof action>();return <main className="public-site"><header className="public-header"><Link className="public-brand" to="/"><span>ZM</span><strong>ZeyherMutter</strong></Link><nav className="public-nav"><Link to="/immobilien">Immobilien</Link><Link to="/kontakt">Kontakt</Link></nav></header><section className="public-hero"><p className="public-eyebrow">Kontakt</p><h1>Wie können wir helfen?</h1><p>Schreiben Sie uns zu Verkauf, Vermietung, Bewertung oder Ihrer Immobiliensuche. Ihre Nachricht landet direkt im ZeyherMutter CRM.</p></section><section className="public-contact-page" id="formular"><div><p className="public-eyebrow">Persönlich</p><h2>Jochen & Sebastian</h2><p>Ihre Anfrage wird intern als normaler CRM-Vorgang erfasst und von uns persönlich bearbeitet.</p></div><div className="public-contact-form-card">{submitted?<div className="public-form-success"><strong>Vielen Dank.</strong><span>Ihre Nachricht wurde übermittelt. Wir melden uns bei Ihnen.</span></div>:<>{result?.error?<div className="public-form-message">{result.error}</div>:null}<Form method="post" className="public-inquiry-form"><div className="public-form-grid"><label><span>Vorname *</span><input name="first_name" required autoComplete="given-name"/></label><label><span>Nachname *</span><input name="last_name" required autoComplete="family-name"/></label></div><div className="public-form-grid"><label><span>E-Mail *</span><input name="email" type="email" required autoComplete="email"/></label><label><span>Telefon</span><input name="phone" type="tel" autoComplete="tel"/></label></div><label><span>Nachricht *</span><textarea name="message" rows={6} minLength={10} maxLength={4000} required/></label><label className="public-honeypot" aria-hidden="true"><span>Firma</span><input name="company" tabIndex={-1} autoComplete="off"/></label><label className="public-consent light"><input type="checkbox" name="consent" required/><span>Ich stimme zu, dass meine Angaben zur Bearbeitung dieser Anfrage gespeichert und verarbeitet werden. *</span></label><button className="public-primary-button dark" type="submit">Nachricht senden</button></Form></>}</div></section><footer className="public-footer"><span>ZeyherMutter · Immobilienvermittlung</span><div><Link to="/impressum">Impressum</Link><Link to="/datenschutz">Datenschutz</Link></div></footer></main>}
