import { data, Link, useLoaderData } from "react-router";
import type { Route } from "./+types/public-properties";
import { createSupabaseServerClient } from "~/lib/supabase.server";
import "~/public-website.css";

const TYPE_LABELS:Record<string,string>={DETACHED_HOUSE:"Einfamilienhaus",SEMI_DETACHED_HOUSE:"Doppelhaushälfte",TERRACED_HOUSE:"Reihenhaus",APARTMENT_BUILDING:"Mehrfamilienhaus",APARTMENT:"Wohnung",PENTHOUSE:"Penthouse",MAISONETTE:"Maisonette",LAND:"Grundstück",COMMERCIAL:"Gewerbe",OFFICE:"Büro",RETAIL:"Einzelhandel",GARAGE:"Garage",PARKING_SPACE:"Stellplatz",OTHER:"Immobilie"};
function money(v:any){return v===null||v===undefined?"Preis auf Anfrage":new Intl.NumberFormat("de-DE",{style:"currency",currency:"EUR",maximumFractionDigits:0}).format(Number(v));}
export function meta(){return[{title:"Immobilien · ZeyherMutter"},{name:"description",content:"Aktuell veröffentlichte Immobilien von ZeyherMutter."}]}
export async function loader({request,context}:Route.LoaderArgs){const {supabase}=createSupabaseServerClient(request,context.cloudflare.env);const {data:rows,error}=await supabase.rpc("public_property_listings");if(error)throw new Response("Immobilien konnten nicht geladen werden.",{status:500});return data({rows:rows??[]},{headers:{"Cache-Control":"public, max-age=60, s-maxage=120"}});}
export default function PublicProperties(){const {rows}=useLoaderData<typeof loader>();return <main className="public-site"><header className="public-header"><Link className="public-brand" to="/immobilien"><span>ZM</span><strong>ZeyherMutter</strong></Link><div>Immobilienvermittlung</div></header><section className="public-hero"><p className="public-eyebrow">Immobilien</p><h1>Aktuelle Angebote.</h1><p>Ausgewählte Immobilien, die derzeit von ZeyherMutter veröffentlicht sind.</p></section><section className="public-property-grid">{rows.map((row:any)=>{const s=row.snapshot??{},a=s.address??{};return <Link className="public-property-card" key={row.public_slug} to={`/immobilien/${row.public_slug}`}><div className="public-property-placeholder"><span>{TYPE_LABELS[s.property_type]??"Immobilie"}</span></div><div className="public-property-card-body"><p className="public-eyebrow">{s.transaction_type==="RENT"?"Zur Miete":"Zum Kauf"}</p><h2>{row.public_title}</h2><p>{row.teaser||s.location_description||[a.city,a.district].filter(Boolean).join(" · ")||"Weitere Informationen im Exposé."}</p><div className="public-property-facts"><strong>{money(s.price)}</strong><span>{s.living_area_sqm?`${Number(s.living_area_sqm)} m²`:""}{s.rooms?` · ${Number(s.rooms)} Zimmer`:""}</span></div></div></Link>})}{rows.length===0?<div className="public-empty"><h2>Aktuell keine veröffentlichten Immobilien.</h2><p>Neue Angebote erscheinen hier nach ihrer Freigabe automatisch.</p></div>:null}</section><footer className="public-footer">ZeyherMutter · Immobilienvermittlung</footer></main>}
