import { data, Form, Link, useLoaderData } from "react-router";
import type { Route } from "./+types/purchase-offers";
import { requirePermission } from "~/lib/auth.server";

const STATUS:Record<string,string>={DRAFT:"Entwurf",SUBMITTED:"Abgegeben",COUNTERED:"Gegenangebot",ACCEPTED:"Angenommen",REJECTED:"Abgelehnt",WITHDRAWN:"Zurückgezogen",REPLACED:"Ersetzt",FAILED:"Abschluss gescheitert"};
const FINANCING:Record<string,string>={OPEN:"Offen",IN_PROGRESS:"In Klärung",CONFIRMED:"Bestätigt",NOT_REQUIRED:"Nicht erforderlich"};
const STATUS_CLASS:Record<string,string>={DRAFT:"status-draft",SUBMITTED:"status-marketing",COUNTERED:"status-contract-pending",ACCEPTED:"status-reserved",REJECTED:"status-lost",WITHDRAWN:"status-withdrawn",REPLACED:"status-archived",FAILED:"status-lost"};
function one(v:any){return Array.isArray(v)?v[0]:v;}
function money(v:any){const n=Number(v);return Number.isFinite(n)?new Intl.NumberFormat("de-DE",{style:"currency",currency:"EUR"}).format(n):"—";}
function formatDate(v:string|null){if(!v)return"—";return new Intl.DateTimeFormat("de-DE",{dateStyle:"medium",timeZone:"Europe/Berlin"}).format(new Date(v));}

export async function loader({request,context}:Route.LoaderArgs){
  const {supabase,responseHeaders,profile}=await requirePermission(request,context.cloudflare.env,"offer.read");
  const url=new URL(request.url);const filters={q:(url.searchParams.get("q")??"").trim(),status:url.searchParams.get("status")??"ACTIVE",propertyId:url.searchParams.get("property_id")??""};
  const [{data:rows,error},{data:canWrite},{data:properties}]=await Promise.all([
    supabase.from("purchase_offers").select("id,offer_number,property_id,contact_id,amount,status,financing_status,submitted_at,valid_until,archived_at,updated_at,properties!inner(id,property_number,internal_title,status),contacts!inner(id,contact_number,first_name,last_name),sale_closings(id,closing_number,status)").order("updated_at",{ascending:false}).limit(500),
    supabase.rpc("current_user_has_permission",{p_permission:"offer.write"}),
    supabase.from("properties").select("id,property_number,internal_title").eq("transaction_type","SALE").is("archived_at",null).order("updated_at",{ascending:false}).limit(500),
  ]);
  if(error)throw new Response("Kaufangebote konnten nicht geladen werden.",{status:500,headers:responseHeaders()});
  const all=(rows??[]) as any[],active=all.filter(r=>!r.archived_at);
  const summary={draft:active.filter(r=>r.status==="DRAFT").length,negotiation:active.filter(r=>["SUBMITTED","COUNTERED"].includes(r.status)).length,accepted:active.filter(r=>r.status==="ACCEPTED").length,failed:active.filter(r=>["REJECTED","WITHDRAWN","FAILED"].includes(r.status)).length};
  const needle=filters.q.toLocaleLowerCase("de-DE");
  const filtered=all.filter(row=>{const p=one(row.properties),c=one(row.contacts);if(filters.propertyId&&row.property_id!==filters.propertyId)return false;if(filters.status==="ACTIVE"&&(row.archived_at||["REJECTED","WITHDRAWN","REPLACED","FAILED"].includes(row.status)))return false;if(filters.status==="ARCHIVED"&&!row.archived_at)return false;if(!["ACTIVE","ALL","ARCHIVED"].includes(filters.status)&&row.status!==filters.status)return false;if(!needle)return true;return [row.offer_number,p?.property_number,p?.internal_title,c?.contact_number,c?.first_name,c?.last_name].filter(Boolean).join(" ").toLocaleLowerCase("de-DE").includes(needle);});
  return data({profile,rows:filtered,summary,canWrite:canWrite===true,properties:properties??[],filters},{headers:responseHeaders()});
}

export default function PurchaseOffers(){const d=useLoaderData<typeof loader>();return <main className="editor-shell">
  <header className="editor-header"><div><Link className="back-link" to="/crm">← CRM</Link><p className="eyebrow">Objekte & Verkauf</p><h1 className="editor-title">Kaufangebote</h1><p className="editor-meta">Angebotsstände, Verhandlung, Annahme und Übergang in den Verkaufsabschluss.</p></div><div className="header-actions">{d.canWrite?<Link className="primary-button link-button" to={d.filters.propertyId?`/purchase-offers/new?property_id=${encodeURIComponent(d.filters.propertyId)}`:"/purchase-offers/new"}>+ Kaufangebot</Link>:null}<span className="badge">{__APP_ENV_LABEL__}</span><small>{d.profile.display_name}</small></div></header>
  <section className="metric-grid"><article className="metric-card"><span>Entwürfe</span><strong>{d.summary.draft}</strong><small>noch bearbeitbar</small></article><article className="metric-card"><span>In Verhandlung</span><strong>{d.summary.negotiation}</strong><small>abgegeben / Gegenangebot</small></article><article className="metric-card"><span>Angenommen</span><strong>{d.summary.accepted}</strong><small>mit Abschlussprozess</small></article><article className="metric-card"><span>Beendet</span><strong>{d.summary.failed}</strong><small>abgelehnt / zurückgezogen / gescheitert</small></article></section>
  <section className="data-card"><Form method="get" className="filter-grid"><label><span>Suche</span><input name="q" defaultValue={d.filters.q} placeholder="Angebot, Objekt oder Käufer"/></label><label><span>Status</span><select name="status" defaultValue={d.filters.status}><option value="ACTIVE">Aktive Vorgänge</option><option value="ALL">Alle</option>{Object.entries(STATUS).map(([v,l])=><option value={v} key={v}>{l}</option>)}<option value="ARCHIVED">Archiviert</option></select></label><label><span>Immobilie</span><select name="property_id" defaultValue={d.filters.propertyId}><option value="">Alle Immobilien</option>{d.properties.map((p:any)=><option key={p.id} value={p.id}>{p.property_number} · {p.internal_title}</option>)}</select></label><button className="secondary-button" type="submit">Filtern</button></Form></section>
  <section className="data-card"><div className="card-head"><div><p className="eyebrow">Angebotsverzeichnis</p><h2>{d.rows.length} Vorgänge</h2></div></div><div className="data-list">{d.rows.map((row:any)=>{const p=one(row.properties),c=one(row.contacts),closing=one(row.sale_closings);return <Link className="data-row data-row-link" to={`/purchase-offers/${row.id}`} key={row.id}><div><strong>{row.offer_number} · {money(row.amount)}</strong><small>{p?.property_number} · {p?.internal_title}</small><small>{c?.first_name} {c?.last_name} · {c?.contact_number}</small></div><div className="row-meta"><span className={`status-pill ${STATUS_CLASS[row.status]??"status-draft"}`}>{row.archived_at?"Archiviert":STATUS[row.status]??row.status}</span><small>{FINANCING[row.financing_status]??(row.financing_status?row.financing_status:"Finanzierung offen")}</small></div><div className="row-meta"><span>{row.submitted_at?`Abgegeben ${formatDate(row.submitted_at)}`:"Noch nicht abgegeben"}</span><small>{row.valid_until?`Gültig bis ${formatDate(row.valid_until)}`:"Keine Befristung"}{closing?.closing_number?` · ${closing.closing_number}`:""}</small></div><span className="subtle-link">Öffnen →</span></Link>})}{d.rows.length===0?<p className="empty-state">Keine Kaufangebote in dieser Ansicht.</p>:null}</div></section>
</main>}
