alter policy profiles_select_self_or_authorized on public.profiles using (user_id = (select auth.uid()) or app_private.has_permission('user.read'));
alter policy user_roles_select_self_or_authorized on public.user_roles using (user_id = (select auth.uid()) or app_private.has_permission('user.read'));
alter policy notifications_select_own on public.notifications using (user_id = (select auth.uid()));
alter policy notifications_update_own on public.notifications using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
alter policy contacts_insert on public.contacts with check (app_private.has_permission('contact.write') and created_by = (select auth.uid()));
alter policy organizations_insert on public.organizations with check (app_private.has_permission('organization.write') and created_by = (select auth.uid()));
alter policy contact_role_assignments_insert on public.contact_role_assignments with check (app_private.has_permission('contact.write') and created_by = (select auth.uid()));
alter policy contact_relationships_insert on public.contact_relationships with check (app_private.has_permission('contact.write') and created_by = (select auth.uid()));
alter policy contact_org_rel_insert on public.contact_organization_relationships with check (app_private.has_permission('contact.write') and created_by = (select auth.uid()));
alter policy tasks_insert on public.tasks with check (app_private.has_permission('task.write') and created_by = (select auth.uid()));
alter policy task_watchers_insert on public.task_watchers with check (app_private.has_permission('task.write') and created_by = (select auth.uid()));
alter policy activity_events_insert_crm on public.activity_events with check (actor_user_id = (select auth.uid()) and (((contact_id is not null) and app_private.has_permission('contact.write')) or contact_id is null));
alter policy comments_insert_crm on public.comments with check (author_user_id = (select auth.uid()) and (((entity_type = any(array['CONTACT'::text,'ORGANIZATION'::text])) and app_private.has_permission('contact.write')) or ((entity_type='TASK'::text) and app_private.has_permission('task.write'))));
alter policy comments_update_own_crm on public.comments using (author_user_id = (select auth.uid())) with check (author_user_id = (select auth.uid()));
alter policy comment_mentions_select on public.comment_mentions using (mentioned_user_id = (select auth.uid()) or app_private.has_permission('user.read'));
alter policy comment_mentions_insert on public.comment_mentions with check (exists (select 1 from public.comments c where c.id = comment_mentions.comment_id and c.author_user_id = (select auth.uid())));
alter policy contact_addresses_insert on public.contact_addresses with check (app_private.has_permission('contact.write') and created_by = (select auth.uid()));

create index if not exists activity_events_actor_user_idx on public.activity_events(actor_user_id);
create index if not exists comment_mentions_mentioned_user_idx on public.comment_mentions(mentioned_user_id);
create index if not exists comments_author_user_idx on public.comments(author_user_id);
create index if not exists contact_addresses_created_by_idx on public.contact_addresses(created_by);
create index if not exists contact_addresses_updated_by_idx on public.contact_addresses(updated_by);
create index if not exists contact_addresses_archived_by_idx on public.contact_addresses(archived_by);
create index if not exists contact_org_rel_created_by_idx on public.contact_organization_relationships(created_by);
create index if not exists contact_relationships_created_by_idx on public.contact_relationships(created_by);
create index if not exists contact_role_assignments_role_idx on public.contact_role_assignments(role_id);
create index if not exists contact_role_assignments_created_by_idx on public.contact_role_assignments(created_by);
create index if not exists contacts_created_by_idx on public.contacts(created_by);
create index if not exists contacts_updated_by_idx on public.contacts(updated_by);
create index if not exists contacts_archived_by_idx on public.contacts(archived_by);
create index if not exists organizations_primary_responsible_idx on public.organizations(primary_responsible_user);
create index if not exists organizations_created_by_idx on public.organizations(created_by);
create index if not exists organizations_updated_by_idx on public.organizations(updated_by);
create index if not exists organizations_archived_by_idx on public.organizations(archived_by);
create index if not exists role_permissions_permission_idx on public.role_permissions(permission_id);
create index if not exists task_watchers_user_idx on public.task_watchers(user_id);
create index if not exists task_watchers_created_by_idx on public.task_watchers(created_by);
create index if not exists tasks_created_by_idx on public.tasks(created_by);
create index if not exists tasks_updated_by_idx on public.tasks(updated_by);
create index if not exists tasks_archived_by_idx on public.tasks(archived_by);
create index if not exists user_roles_role_idx on public.user_roles(role_id);
create index if not exists user_roles_assigned_by_idx on public.user_roles(assigned_by);
create index if not exists user_roles_revoked_by_idx on public.user_roles(revoked_by);
